import { defineMoveset } from "../move-data.js";

export const EMBER_DATA_VERSION = Object.freeze({
  game: "THE KING OF FIGHTERS XV",
  characterBasis: "Kyo Kusanagi",
  version: "2.51",
  balanceDataVersion: "2.50",
  commandSource: "SNK official command list",
  frameSource: "Dream Cancel Kyo data, revision 2026-07-11",
  note: "Kyo received no gameplay changes in patch 2.51.",
});

const VERIFIED = "verified-v2.51-command+current-community-frame";
const SYSTEM_VERIFIED = "official-system+current-community-frame";
const INFERRED = "current-community-schema-inference";
const NEEDS_LAB = "needsLab";

const NO_CANCEL = Object.freeze({ tier: "none", hitMask: [] });
const COMMAND_CANCEL = Object.freeze({ tier: "command", on: ["hit", "block"] });
const SPECIAL_CANCEL = Object.freeze({ tier: "special", on: ["hit", "block"] });
const SUPER_CANCEL = Object.freeze({ tier: "super", on: ["hit", "block"] });
const NO_KNOCKDOWN = Object.freeze({ type: "none" });
const NO_JUGGLE = Object.freeze({ mode: "none", cost: 0 });

// Yakumo is a 13-impact cinematic, not 13 damage packets on one collision
// frame. Each entry owns a distinct authored window; hitstop then gives every
// impact enough screen time for the combo counter and health bar to advance.
const YAKUMO_CINEMATIC_GAPS = Object.freeze([2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 3, 0]);
const YAKUMO_CINEMATIC_HITSTOP = Object.freeze([8, 5, 5, 4, 4, 4, 4, 5, 4, 4, 5, 7, 14]);
const YAKUMO_CINEMATIC_PATTERN = Object.freeze(YAKUMO_CINEMATIC_GAPS.map((gapAfter, index) => Object.freeze({
  id: index === 0 ? "hit1" : `scriptedHit${index + 1}`,
  frames: index === 0 || index === YAKUMO_CINEMATIC_GAPS.length - 1 ? 2 : 1,
  ...(gapAfter > 0 ? { gapAfter } : {}),
})));
const YAKUMO_CINEMATIC_HIT_OVERRIDES = Object.freeze(YAKUMO_CINEMATIC_HITSTOP.map((hitstop, index) => Object.freeze({
  hitstop,
  // Keep the captured target in the cinematic until the terminal launch.
  knockback: index === YAKUMO_CINEMATIC_HITSTOP.length - 1 ? 4 : 0,
})));

const COMMAND_NORMAL_SOURCES = Object.freeze([
  "closeA",
  "closeB",
  "closeC",
  "closeD",
  "crouchA",
  "crouchC",
  "sweep",
  "blowbackGround",
]);

const CANCEL_TARGETS = Object.freeze({
  command: ["commandNormal", "special", "super", "climax"],
  special: ["special", "super", "climax"],
  super: ["super", "climax"],
  advanced: ["super", "climax"],
  climax: ["climax"],
  branch: ["targetCombo"],
});

function command(label, buttons = [], options = {}) {
  return { buttons, label, ...options };
}

function phaseWindows(startup, pattern = [1]) {
  let cursor = startup;
  return pattern.map((entry, index) => {
    const phase = typeof entry === "number" ? { frames: entry } : entry;
    const frames = Math.max(1, Number(phase.frames) || 1);
    const id = String(phase.id ?? `hit${index + 1}`);
    const window = {
      id,
      hitId: String(phase.hitId ?? id),
      start: cursor,
      end: cursor + frames - 1,
    };
    cursor = window.end + 1 + Math.max(0, Number(phase.gapAfter) || 0);
    return window;
  });
}

function normalizeCancelRules(cancel, windows) {
  if (!cancel || cancel.tier === "none") return [];
  const rules = cancel.rules ?? [cancel];
  return rules.map((rule) => {
    const indexes = rule.hitIndexes ?? windows.map((_, index) => index);
    const selected = indexes.map((index) => windows[index]).filter(Boolean);
    const first = selected[0] ?? windows[0];
    const last = selected[selected.length - 1] ?? windows[windows.length - 1];
    return {
      start: rule.start ?? first.start,
      end: rule.end ?? last.end,
      on: rule.on ?? ["hit", "block"],
      into: rule.into ?? CANCEL_TARGETS[rule.tier] ?? [],
      moves: rule.moves ?? [],
      requiresContact: rule.requiresContact !== false,
      delayable: Boolean(rule.delayable),
    };
  });
}

function authoredMove(config) {
  const {
    name,
    command: authoredCommand,
    category = "normal",
    startup,
    pattern = [1],
    recovery,
    damage = 0,
    damageHits = [damage],
    hit = {},
    hitOverrides = [],
    cancel = NO_CANCEL,
    cost = {},
    routeFrom = [],
    routeTo = [],
    knockdown = NO_KNOCKDOWN,
    juggle = NO_JUGGLE,
    tags = [],
    animation,
    dataConfidence = VERIFIED,
    stance = "ground",
    strength = "",
    ...extra
  } = config;
  const activeWindows = phaseWindows(startup, pattern);
  const hitLevel = hit.level ?? "mid";
  const authoredHits = damageHits.map((hitDamage, index) => {
    const window = activeWindows[Math.min(index, activeWindows.length - 1)];
    const override = hitOverrides[index] ?? {};
    const isLast = index === damageHits.length - 1;
    return {
      id: String(override.id ?? (index < activeWindows.length ? window.hitId : `scriptedHit${index + 1}`)),
      start: override.start ?? window.start,
      end: override.end ?? window.end,
      damage: hitDamage,
      hitLevel: override.hitLevel ?? hitLevel,
      knockdownType: override.knockdownType ?? (isLast && knockdown.type !== "none" ? knockdown.type : undefined),
      juggleCost: override.juggleCost ?? (isLast ? juggle.cost : undefined),
      juggleLimit: override.juggleLimit ?? (isLast ? juggle.limit : undefined),
      groundBounces: override.groundBounces ?? (isLast ? knockdown.groundBounces : undefined),
      wallBounces: override.wallBounces ?? (isLast ? knockdown.wallBounces : undefined),
      initialProration: override.initialProration ?? hit.initialProration,
      scalingStep: override.scalingStep ?? hit.scalingStep,
      minimumScaling: override.minimumScaling ?? hit.minimumScaling,
      ...override,
    };
  });

  return {
    ...extra,
    name,
    command: authoredCommand,
    commandLabel: authoredCommand?.label ?? "",
    category,
    startup,
    activeWindows,
    recovery,
    damage,
    damageHits: [...damageHits],
    hit: { level: hitLevel, ...hit },
    hitLevel,
    hits: authoredHits,
    cancel,
    cancels: normalizeCancelRules(cancel, activeWindows),
    cost: { ...cost },
    routeFrom: [...routeFrom],
    routeTo: [...routeTo],
    knockdown: { ...knockdown },
    knockdownType: knockdown.type === "none" ? undefined : knockdown.type,
    groundBounces: knockdown.groundBounces,
    wallBounces: knockdown.wallBounces,
    quickRiseWindow: knockdown.type === "soft" ? 8 : undefined,
    maximumDelayRise: knockdown.type === "soft" ? 18 : undefined,
    juggle: { ...juggle },
    juggleCost: juggle.cost,
    juggleLimit: juggle.limit,
    tags: [...tags],
    animation,
    dataConfidence,
    sourceVersion: "2.51",
    stance,
    strength,
  };
}

const moves = {
  // Close standing normals -------------------------------------------------
  closeA: authoredMove({
    name: "Close A",
    command: command("c.A", ["lp"], { stance: "close" }),
    startup: 4,
    pattern: [2],
    recovery: 8,
    damage: 25,
    hit: { level: "mid", advantage: 5, blockAdvantage: 3 },
    cancel: COMMAND_CANCEL,
    tags: ["normal", "close", "fast", "frameTrap", "comboStarter"],
    animation: "highLight",
    strength: "light",
  }),
  closeB: authoredMove({
    name: "Close B",
    command: command("c.B", ["lk"], { stance: "close" }),
    startup: 5,
    pattern: [2],
    recovery: 13,
    damage: 30,
    hit: { level: "low", advantage: 0, blockAdvantage: -2 },
    cancel: COMMAND_CANCEL,
    tags: ["normal", "close", "low", "comboStarter"],
    animation: "lowLight",
    strength: "light",
  }),
  closeC: authoredMove({
    name: "Close C",
    command: command("c.C", ["hp"], { stance: "close" }),
    startup: 4,
    pattern: [3],
    recovery: 19,
    damage: 70,
    hit: { level: "mid", advantage: -1, blockAdvantage: -3 },
    cancel: COMMAND_CANCEL,
    tags: ["normal", "close", "heavy", "punish", "comboStarter"],
    animation: "highHeavy",
    strength: "heavy",
  }),
  closeD: authoredMove({
    name: "Close D",
    command: command("c.D", ["hk"], { stance: "close" }),
    startup: 6,
    pattern: [2],
    recovery: 20,
    damage: 80,
    hit: { level: "mid", advantage: -1, blockAdvantage: -3 },
    cancel: COMMAND_CANCEL,
    tags: ["normal", "close", "heavy", "optimalPunishStarter"],
    animation: "highHeavy",
    strength: "heavy",
  }),

  // Far standing normals ---------------------------------------------------
  farA: authoredMove({
    name: "Far A",
    command: command("f.A", ["lp"], { stance: "far" }),
    startup: 6,
    pattern: [2],
    recovery: 14,
    damage: 25,
    hit: { level: "mid", advantage: -1, blockAdvantage: -3 },
    cancel: SPECIAL_CANCEL,
    tags: ["normal", "far", "poke", "antiAir"],
    animation: "midLight",
    strength: "light",
  }),
  farB: authoredMove({
    name: "Far B",
    command: command("f.B", ["lk"], { stance: "far" }),
    startup: 6,
    pattern: [2],
    recovery: 13,
    damage: 30,
    hit: { level: "mid", advantage: 0, blockAdvantage: -2 },
    cancel: SUPER_CANCEL,
    tags: ["normal", "far", "poke", "hitConfirm"],
    animation: "midLight",
    strength: "light",
  }),
  farC: authoredMove({
    name: "Far C",
    command: command("f.C", ["hp"], { stance: "far" }),
    startup: 10,
    pattern: [3],
    recovery: 19,
    damage: 70,
    hit: { level: "mid", advantage: -1, blockAdvantage: -3 },
    cancel: SPECIAL_CANCEL,
    tags: ["normal", "far", "longRange", "whiffPunish", "comboStarter"],
    animation: "midHeavy",
    strength: "heavy",
  }),
  farD: authoredMove({
    name: "Far D",
    command: command("f.D", ["hk"], { stance: "far" }),
    startup: 8,
    pattern: [4],
    recovery: 20,
    damage: 90,
    hit: {
      level: "mid",
      advantage: -3,
      blockAdvantage: -5,
      invulnerability: [{ type: "low", start: 8, end: 17 }],
    },
    cancel: SUPER_CANCEL,
    tags: ["normal", "far", "longRange", "lowCrush"],
    animation: "midHeavy",
    strength: "heavy",
  }),

  // Crouching normals ------------------------------------------------------
  crouchA: authoredMove({
    name: "Crouch A",
    command: command("2A", ["lp"], { direction: "down", stance: "crouch" }),
    startup: 4,
    pattern: [3],
    recovery: 9,
    damage: 25,
    hit: { level: "mid", advantage: 3, blockAdvantage: 1 },
    cancel: COMMAND_CANCEL,
    tags: ["normal", "crouch", "fast", "frameTrap", "comboStarter"],
    animation: "lowLight",
    strength: "light",
  }),
  crouchB: authoredMove({
    name: "Crouch B",
    command: command("2B", ["lk"], { direction: "down", stance: "crouch" }),
    startup: 5,
    pattern: [3],
    recovery: 10,
    damage: 30,
    hit: { level: "low", advantage: 2, blockAdvantage: 0 },
    cancel: SUPER_CANCEL,
    tags: ["normal", "crouch", "low", "comboStarter"],
    animation: "lowLight",
    strength: "light",
  }),
  crouchC: authoredMove({
    name: "Crouch C",
    command: command("2C", ["hp"], { direction: "down", stance: "crouch" }),
    startup: 7,
    pattern: [4],
    recovery: 19,
    damage: 70,
    hit: { level: "mid", advantage: -2, blockAdvantage: -4 },
    cancel: COMMAND_CANCEL,
    tags: ["normal", "crouch", "antiAir", "comboStarter"],
    animation: "lowHeavy",
    strength: "heavy",
  }),
  sweep: authoredMove({
    name: "Crouch D",
    command: command("2D", ["hk"], { direction: "down", stance: "crouch" }),
    startup: 7,
    pattern: [4],
    recovery: 23,
    damage: 80,
    hit: { level: "low", blockAdvantage: -8 },
    cancel: COMMAND_CANCEL,
    knockdown: { type: "soft", techAdvantage: 22, nonTechAdvantage: 49 },
    tags: ["normal", "crouch", "low", "sweep", "softKnockdown"],
    animation: "lowHeavy",
    strength: "heavy",
  }),

  // Hop and jump normals. The source has no separate Kyo nj.* rows: vertical
  // hop/hyper-hop share h.*, and vertical normal/hyper-jump share j.*.
  hopA: authoredMove({
    name: "Hop A",
    command: command("h.A", ["lp"], { air: true, stance: "hop" }),
    startup: 4,
    pattern: [5],
    recovery: 1,
    damage: 40,
    hit: { level: "overhead", landingRecovery: 1, jumpModes: ["hop", "verticalHop", "hyperHop"] },
    tags: ["normal", "air", "hop", "overhead", "verticalSharedData"],
    animation: "airLight",
    dataConfidence: INFERRED,
    stance: "air",
    strength: "light",
  }),
  jumpA: authoredMove({
    name: "Jump A",
    command: command("j.A", ["lp"], { air: true, stance: "jump" }),
    startup: 4,
    pattern: [5],
    recovery: 1,
    damage: 45,
    hit: { level: "overhead", landingRecovery: 1, jumpModes: ["jump", "verticalJump", "hyperJump"] },
    tags: ["normal", "air", "jump", "overhead", "verticalSharedData"],
    animation: "airLight",
    dataConfidence: INFERRED,
    stance: "air",
    strength: "light",
  }),
  hopB: authoredMove({
    name: "Hop B",
    command: command("h.B", ["lk"], { air: true, stance: "hop" }),
    startup: 5,
    pattern: [9],
    recovery: 1,
    damage: 40,
    hit: { level: "overhead", landingRecovery: 1, jumpModes: ["hop", "verticalHop", "hyperHop"] },
    tags: ["normal", "air", "hop", "overhead", "verticalSharedData"],
    animation: "airLight",
    dataConfidence: INFERRED,
    stance: "air",
    strength: "light",
  }),
  jumpB: authoredMove({
    name: "Jump B",
    command: command("j.B", ["lk"], { air: true, stance: "jump" }),
    startup: 5,
    pattern: [10],
    recovery: 1,
    damage: 45,
    hit: { level: "overhead", landingRecovery: 1, jumpModes: ["jump", "verticalJump", "hyperJump"] },
    tags: ["normal", "air", "jump", "overhead", "crossup", "verticalSharedData"],
    animation: "airLight",
    dataConfidence: INFERRED,
    stance: "air",
    strength: "light",
  }),
  hopC: authoredMove({
    name: "Hop C",
    command: command("h.C", ["hp"], { air: true, stance: "hop" }),
    startup: 6,
    pattern: [8],
    recovery: 1,
    damage: 70,
    hit: { level: "overhead", landingRecovery: 1, jumpModes: ["hop", "verticalHop", "hyperHop"] },
    tags: ["normal", "air", "hop", "overhead", "jumpIn", "verticalSharedData"],
    animation: "airHeavy",
    dataConfidence: INFERRED,
    stance: "air",
    strength: "heavy",
  }),
  jumpC: authoredMove({
    name: "Jump C",
    command: command("j.C", ["hp"], { air: true, stance: "jump" }),
    startup: 6,
    pattern: [8],
    recovery: 1,
    damage: 70,
    hit: { level: "overhead", landingRecovery: 1, jumpModes: ["jump", "verticalJump", "hyperJump"] },
    tags: ["normal", "air", "jump", "overhead", "jumpIn", "verticalSharedData"],
    animation: "airHeavy",
    dataConfidence: INFERRED,
    stance: "air",
    strength: "heavy",
  }),
  hopD: authoredMove({
    name: "Hop D",
    command: command("h.D", ["hk"], { air: true, stance: "hop" }),
    startup: 8,
    pattern: [5],
    recovery: 1,
    damage: 70,
    hit: { level: "overhead", landingRecovery: 1, jumpModes: ["hop", "verticalHop", "hyperHop"] },
    tags: ["normal", "air", "hop", "overhead", "verticalSharedData"],
    animation: "airHeavy",
    dataConfidence: INFERRED,
    stance: "air",
    strength: "heavy",
  }),
  jumpD: authoredMove({
    name: "Jump D",
    command: command("j.D", ["hk"], { air: true, stance: "jump" }),
    startup: 8,
    pattern: [5],
    recovery: 1,
    damage: 70,
    hit: { level: "overhead", landingRecovery: 1, jumpModes: ["jump", "verticalJump", "hyperJump"] },
    tags: ["normal", "air", "jump", "overhead", "jumpIn", "verticalSharedData"],
    animation: "airHeavy",
    dataConfidence: INFERRED,
    stance: "air",
    strength: "heavy",
  }),

  // Command normals --------------------------------------------------------
  gofuYo: authoredMove({
    name: "Ge Shiki: Gofu Yo",
    command: command("6B", ["lk"], { direction: "forward" }),
    category: "commandNormal",
    startup: 23,
    pattern: [2],
    recovery: 21,
    damage: 75,
    hit: { level: "overhead", advantage: -2, blockAdvantage: -4, version: "raw" },
    cancel: SUPER_CANCEL,
    routeTo: ["gofuYoCanceled"],
    tags: ["commandNormal", "overhead", "rawVersion"],
    animation: "midHeavy",
    strength: "heavy",
  }),
  gofuYoCanceled: authoredMove({
    name: "Ge Shiki: Gofu Yo (Canceled Version)",
    command: command("[normal] > 6B", ["lk"], { direction: "forward" }),
    category: "commandNormal",
    startup: 15,
    pattern: [2],
    recovery: 18,
    damage: 50,
    hit: { level: "overhead", advantage: 1, blockAdvantage: -1, version: "normalCancel" },
    cancel: SPECIAL_CANCEL,
    routeFrom: COMMAND_NORMAL_SOURCES,
    tags: ["commandNormal", "overhead", "cancelVersion", "combo"],
    animation: "midHeavy",
    strength: "heavy",
  }),
  shiki88: authoredMove({
    name: "88 Shiki",
    command: command("3D", ["hk"], { direction: "downForward" }),
    category: "commandNormal",
    startup: 7,
    pattern: [{ id: "low", frames: 2, gapAfter: 6 }, { id: "mid", frames: 2 }],
    recovery: 21,
    damage: 70,
    damageHits: [30, 40],
    hit: { level: "low", levels: ["low", "mid"], advantage: -8, blockAdvantage: -10, version: "raw" },
    hitOverrides: [{ hitLevel: "low" }, { hitLevel: "mid" }],
    cancel: {
      tier: "mixed",
      rules: [
        { tier: "special", hitIndexes: [0], on: ["hit", "block"] },
        { tier: "super", hitIndexes: [0, 1], on: ["hit", "block"] },
      ],
    },
    routeTo: ["shiki88Canceled"],
    tags: ["commandNormal", "low", "multiHit", "rawVersion"],
    animation: "lowHeavy",
    strength: "heavy",
  }),
  shiki88Canceled: authoredMove({
    name: "88 Shiki (Canceled Version)",
    command: command("[normal] > 3D", ["hk"], { direction: "downForward" }),
    category: "commandNormal",
    startup: 11,
    pattern: [{ id: "low", frames: 2, gapAfter: 6 }, { id: "mid", frames: 2 }],
    recovery: 21,
    damage: 70,
    damageHits: [30, 40],
    hit: { level: "low", levels: ["low", "mid"], advantage: -8, blockAdvantage: -10, version: "normalCancel" },
    hitOverrides: [{ hitLevel: "low" }, { hitLevel: "mid" }],
    cancel: {
      tier: "mixed",
      rules: [
        { tier: "special", hitIndexes: [0], on: ["hit", "block"] },
        { tier: "super", hitIndexes: [0, 1], on: ["hit", "block"] },
      ],
    },
    routeFrom: COMMAND_NORMAL_SOURCES,
    tags: ["commandNormal", "low", "multiHit", "cancelVersion", "combo"],
    animation: "lowHeavy",
    strength: "heavy",
  }),
  narakuOtoshi: authoredMove({
    name: "Ge Shiki: Naraku Otoshi",
    command: command("j.2C", ["hp"], { air: true, direction: "down" }),
    category: "commandNormal",
    startup: 12,
    pattern: [4],
    recovery: 1,
    damage: 80,
    hit: {
      level: "overhead",
      advantageByHeight: { lowest: 15, highest: 4 },
      blockAdvantageByHeight: { lowest: 12, highest: 1 },
      landingRecovery: 1,
      patch250: ["increased blockstun", "reduced overall recovery", "rear hitbox expanded"],
    },
    tags: ["commandNormal", "air", "overhead", "crossup", "patch250"],
    animation: "airHammer",
    stance: "air",
    strength: "heavy",
  }),

  // Blowbacks --------------------------------------------------------------
  blowbackGround: authoredMove({
    name: "Standing Blowback",
    command: command("C+D", ["hp", "hk"], { chord: true }),
    category: "commandNormal",
    startup: 16,
    pattern: [5],
    recovery: 20,
    damage: 75,
    hit: {
      level: "mid",
      blockAdvantageByRange: { close: -2, maximum: 2 },
      groundResult: "wallSplatToHardKnockdown",
      airResult: "softKnockdown",
    },
    cancel: COMMAND_CANCEL,
    knockdown: { type: "wallBounce", wallBounces: 1, terminal: "hard", airHitType: "soft", advantageRange: [75, 91] },
    juggle: { mode: "wallSplat", cost: 1, limit: 10 },
    tags: ["blowback", "wallSplat", "hardKnockdown", "softKnockdown", "comboStarter"],
    animation: "highHeavy",
    strength: "heavy",
  }),
  blowbackHop: authoredMove({
    name: "Hop Blowback",
    command: command("h.CD", ["hp", "hk"], { chord: true, air: true, stance: "hop" }),
    category: "commandNormal",
    startup: 14,
    pattern: [6],
    recovery: 1,
    damage: 80,
    hit: { level: "mid", landingRecovery: 1 },
    knockdown: { type: "soft" },
    juggle: { mode: "airReset", cost: 1, limit: 10 },
    tags: ["blowback", "air", "hop", "softKnockdown", "counterHitJuggle"],
    animation: "airHeavy",
    stance: "air",
    strength: "heavy",
  }),
  blowbackJump: authoredMove({
    name: "Jump Blowback",
    command: command("j.CD", ["hp", "hk"], { chord: true, air: true, stance: "jump" }),
    category: "commandNormal",
    startup: 14,
    pattern: [8],
    recovery: 1,
    damage: 90,
    hit: { level: "mid", landingRecovery: 1 },
    knockdown: { type: "soft" },
    juggle: { mode: "airReset", cost: 1, limit: 10 },
    tags: ["blowback", "air", "jump", "softKnockdown", "counterHitJuggle"],
    animation: "airHeavy",
    stance: "air",
    strength: "heavy",
  }),

  // Throws and Rush --------------------------------------------------------
  hatsugane: authoredMove({
    name: "Hatsugane",
    command: command("close 4/6+C", ["hp"], { direction: "backOrForward", stance: "close" }),
    category: "throw",
    startup: 1,
    pattern: [1],
    recovery: 0,
    damage: 100,
    hit: { level: "throw", unblockable: true, throwTechWindow: 11 },
    knockdown: { type: "hard", advantage: 22 },
    tags: ["throw", "groundThrow", "hardKnockdown", "unblockable"],
    animation: "throw",
  }),
  issetsuSeoiNage: authoredMove({
    name: "Issetsu Seoi Nage",
    command: command("close 4/6+D", ["hk"], { direction: "backOrForward", stance: "close" }),
    category: "throw",
    startup: 1,
    pattern: [1],
    recovery: 0,
    damage: 100,
    damageHits: [50, 50],
    hit: { level: "throw", unblockable: true, throwTechWindow: 11, scriptedSequence: true },
    knockdown: { type: "hard", advantage: 30 },
    tags: ["throw", "groundThrow", "hardKnockdown", "unblockable", "multiHit"],
    animation: "throw",
  }),
  rush1: authoredMove({
    name: "Rush 1",
    command: command("c.A > A", ["lp"], { stance: "close" }),
    category: "targetCombo",
    startup: 9,
    pattern: [1],
    recovery: 1,
    damage: 48,
    damageHits: [25, 25],
    hit: { level: "mid", advantage: -5, blockAdvantage: -7, activeRecoveryUnavailable: true },
    cancel: { tier: "branch", moves: ["rush2"], on: ["hit", "block"], requiresContact: true },
    routeTo: ["rush2"],
    tags: ["rush", "targetCombo", "multiHit", "needsActiveRecoveryLab"],
    animation: "highLight",
    dataConfidence: NEEDS_LAB,
    needsLab: true,
  }),
  rush2: authoredMove({
    name: "Rush 2",
    command: command("c.A > A > X", ["lp"], { stance: "close" }),
    category: "targetCombo",
    startup: 6,
    pattern: [1],
    recovery: 1,
    damage: 70,
    damageHits: [25, 25, 25],
    hit: { level: "mid", advantage: -6, blockAdvantage: -8, activeRecoveryUnavailable: true },
    cancel: {
      tier: "branch",
      moves: ["aragami", "orochinagiLight", "maxOrochinagi", "yakumo"],
      on: ["hit", "block"],
      requiresContact: true,
    },
    routeFrom: ["rush1"],
    routeTo: ["aragami", "orochinagiLight", "maxOrochinagi", "yakumo"],
    tags: ["rush", "targetCombo", "multiHit", "adaptiveFinisher", "needsActiveRecoveryLab"],
    animation: "highHeavy",
    dataConfidence: NEEDS_LAB,
    needsLab: true,
  }),

  // 100 Shiki: Oniyaki ----------------------------------------------------
  oniyakiLight: authoredMove({
    name: "100 Shiki: Oniyaki (A)",
    command: command("623A", ["lp"], { motion: "dp" }),
    category: "special",
    startup: 4,
    pattern: [{ id: "rise", frames: 4, gapAfter: 1 }, { id: "crest", frames: 4 }],
    recovery: 42,
    damage: 78,
    damageHits: [55, 25],
    hit: {
      level: "mid",
      blockAdvantage: -27,
      invulnerability: [{ type: "nonProjectileAirStrike", start: 1, end: 5 }],
    },
    cancel: { tier: "super", hitIndexes: [0], on: ["hit", "block"] },
    knockdown: { type: "soft", techAdvantage: 23, nonTechAdvantage: 50 },
    juggle: { mode: "launcher", cost: 1, limit: 10 },
    tags: ["special", "dragonPunch", "antiAir", "reversal", "multiHit", "softKnockdown"],
    animation: "dragonPunch",
    strength: "light",
  }),
  oniyakiHeavy: authoredMove({
    name: "100 Shiki: Oniyaki (C)",
    command: command("623C", ["hp"], { motion: "dp" }),
    category: "special",
    startup: 7,
    pattern: [{ id: "first", frames: 3 }, { id: "second", frames: 6 }, { id: "third", frames: 6 }],
    recovery: 48,
    damage: 135,
    damageHits: [80, 30, 30],
    hit: {
      level: "mid",
      blockAdvantage: -35,
      reportedDamage: 135,
      rawHitDamage: 140,
      invulnerability: [{ type: "fullBody", start: 1, end: 10 }],
    },
    cancel: { tier: "super", hitIndexes: [0], on: ["hit", "block"] },
    knockdown: { type: "soft", techAdvantage: 16, nonTechAdvantage: 43 },
    juggle: { mode: "launcher", cost: 1, limit: 10 },
    tags: ["special", "dragonPunch", "reversal", "multiHit", "softKnockdown"],
    animation: "dragonPunch",
    strength: "heavy",
  }),
  oniyakiEx: authoredMove({
    name: "EX 100 Shiki: Oniyaki",
    command: command("623AC", ["lp", "hp"], { motion: "dp", chord: true }),
    category: "od",
    startup: 4,
    pattern: Array.from({ length: 10 }, (_, index) => ({ id: `contact${index + 1}`, frames: 3 })),
    recovery: 53,
    damage: 170,
    damageHits: [40, 15, 15, 15, 15, 15, 15, 15, 15, 15, 40],
    hit: {
      level: "mid",
      blockAdvantage: -45,
      reportedDamageRange: [170, 200],
      scriptedFinisherSharesLastWindow: true,
      invulnerability: [{ type: "fullBody", start: 1, end: 9 }],
    },
    cost: { super: 50 },
    knockdown: { type: "soft", techAdvantage: 10, nonTechAdvantage: 50 },
    juggle: { mode: "launcher", cost: 1, limit: 10 },
    tags: ["special", "ex", "dragonPunch", "reversal", "multiHit", "softKnockdown"],
    animation: "dragonPunch",
    strength: "ex",
  }),

  // R.E.D. Kick ------------------------------------------------------------
  redKickLight: authoredMove({
    name: "R.E.D. Kick (B)",
    command: command("4214B", ["lk"], { motion: "rdp" }),
    category: "special",
    startup: 19,
    pattern: [6],
    recovery: 18,
    damage: 70,
    hit: { level: "mid", blockAdvantageByStance: { standing: -4, crouching: -2 } },
    knockdown: { type: "hard", advantageByStance: { standing: 42, crouching: 44 } },
    tags: ["special", "redKick", "hardKnockdown", "extendedReverseDP"],
    animation: "airTatsu",
    strength: "light",
  }),
  redKickHeavy: authoredMove({
    name: "R.E.D. Kick (D)",
    command: command("4214D", ["hk"], { motion: "rdp" }),
    category: "special",
    startup: 30,
    pattern: [8],
    recovery: 14,
    damage: 130,
    hit: { level: "mid", blockAdvantageByStance: { standing: 1, crouching: 2 } },
    knockdown: { type: "hard", advantageByStance: { standing: 47, crouching: 48 } },
    tags: ["special", "redKick", "hardKnockdown", "plusOnBlock", "extendedReverseDP"],
    animation: "airTatsu",
    strength: "heavy",
  }),
  redKickEx: authoredMove({
    name: "EX R.E.D. Kick",
    command: command("4214BD", ["lk", "hk"], { motion: "rdp", chord: true }),
    category: "od",
    startup: 18,
    pattern: [7],
    recovery: 16,
    damage: 100,
    hit: { level: "mid", blockAdvantageByStance: { standing: -7, crouching: -4 } },
    cost: { super: 50 },
    knockdown: { type: "groundBounce", groundBounces: 1, terminal: "hard", advantageRange: [69, 74] },
    juggle: { mode: "groundBounce", cost: 1, limit: 10 },
    tags: ["special", "ex", "redKick", "groundBounce", "combo", "extendedReverseDP"],
    animation: "airTatsu",
    strength: "ex",
  }),

  // 75 Shiki: Kai ----------------------------------------------------------
  kaiLight: authoredMove({
    name: "75 Shiki: Kai (B)",
    command: command("236B", ["lk"], { motion: "qcf" }),
    category: "special",
    startup: 15,
    pattern: [4],
    recovery: 30,
    damage: 30,
    hit: { level: "mid", advantage: -19, blockAdvantage: -21 },
    cancel: { tier: "branch", moves: ["kaiFollowLight"], on: ["hit", "block", "whiff"], requiresContact: false, delayable: true },
    routeTo: ["kaiFollowLight"],
    tags: ["special", "kai", "rekkaStarter"],
    animation: "rekkaLight",
    strength: "light",
  }),
  kaiHeavy: authoredMove({
    name: "75 Shiki: Kai (D)",
    command: command("236D", ["hk"], { motion: "qcf" }),
    category: "special",
    startup: 20,
    pattern: [5],
    recovery: 29,
    damage: 30,
    hit: { level: "mid", blockAdvantage: -21 },
    cancel: { tier: "branch", moves: ["kaiFollowHeavy"], on: ["hit", "block", "whiff"], requiresContact: false, delayable: true },
    routeTo: ["kaiFollowHeavy"],
    knockdown: { type: "launch", terminal: "soft", techAdvantage: 20, nonTechAdvantage: 47 },
    juggle: { mode: "launcher", cost: 1, limit: 10 },
    tags: ["special", "kai", "launcher", "softKnockdown", "rekkaStarter"],
    animation: "rekkaHeavy",
    strength: "heavy",
  }),
  kaiEx: authoredMove({
    name: "EX 75 Shiki: Kai",
    command: command("236BD", ["lk", "hk"], { motion: "qcf", chord: true }),
    category: "od",
    startup: 10,
    pattern: [{ id: "first", frames: 3, gapAfter: 6 }, { id: "second", frames: 4 }],
    recovery: 19,
    damage: 40,
    // The current table publishes only the 40-point aggregate. Keep that truth
    // explicit instead of inventing an even per-hit split for the simulator.
    damageHits: [40, 0],
    hit: {
      level: "mid",
      blockAdvantage: { standing: -6, crouchingFirstHitOnly: -13 },
      aggregateDamage: 40,
      perHitDamageNeedsLab: true,
    },
    cost: { super: 50 },
    knockdown: { type: "launch", terminal: "soft", techAdvantage: 55, nonTechAdvantage: 82 },
    juggle: { mode: "launcher", cost: 1, limit: 10 },
    tags: ["special", "ex", "kai", "launcher", "multiHit", "softKnockdown"],
    animation: "rekkaHeavy",
    strength: "ex",
    dataConfidence: INFERRED,
  }),
  kaiFollowLight: authoredMove({
    name: "75 Shiki: Kai Follow-up (after B)",
    command: command("[236B] > B/D", ["lk"]),
    category: "targetCombo",
    startup: 6,
    pattern: [9],
    recovery: 14,
    damage: 30,
    hit: { level: "mid", blockAdvantage: -6, acceptedButtons: ["B", "D"] },
    routeFrom: ["kaiLight"],
    knockdown: { type: "launch", terminal: "soft", techAdvantage: 44, nonTechAdvantage: 71 },
    juggle: { mode: "launcher", cost: 1, limit: 10 },
    tags: ["specialFollowup", "kai", "launcher", "softKnockdown"],
    animation: "rekkaLight",
    strength: "light",
    inputVariants: ["lk", "hk"],
  }),
  kaiFollowHeavy: authoredMove({
    name: "75 Shiki: Kai Follow-up (after D)",
    command: command("[236D] > B/D", ["hk"]),
    category: "targetCombo",
    startup: 6,
    pattern: [9],
    recovery: 14,
    damage: 30,
    hit: { level: "mid", blockAdvantage: -6, acceptedButtons: ["B", "D"] },
    routeFrom: ["kaiHeavy"],
    knockdown: { type: "launch", terminal: "soft", techAdvantage: 53, nonTechAdvantage: 80, immediateFollowup: true },
    juggle: { mode: "launcher", cost: 1, limit: 10 },
    tags: ["specialFollowup", "kai", "launcher", "softKnockdown"],
    animation: "rekkaHeavy",
    strength: "heavy",
    inputVariants: ["lk", "hk"],
  }),

  // Aragami route tree -----------------------------------------------------
  aragami: authoredMove({
    name: "114 Shiki: Aragami",
    command: command("236A", ["lp"], { motion: "qcf" }),
    category: "special",
    startup: 11,
    pattern: [6],
    recovery: 21,
    damage: 60,
    hit: {
      level: "mid",
      advantage: -6,
      blockAdvantage: -8,
      armor: [{ type: "midBody", start: 5, end: 6 }],
    },
    cancel: {
      tier: "mixed",
      rules: [
        { tier: "super", on: ["hit", "block"] },
        {
          tier: "branch",
          moves: ["konokizu", "yanosabi2", "munotsuchi"],
          on: ["hit", "block", "whiff"],
          requiresContact: false,
          delayable: true,
        },
      ],
    },
    routeTo: ["konokizu", "yanosabi2", "munotsuchi"],
    tags: ["special", "rekka", "aragamiTree", "armor", "combo"],
    animation: "rekkaLight",
    strength: "light",
  }),
  konokizu: authoredMove({
    name: "128 Shiki: Konokizu",
    command: command("[Aragami] > 236P", ["lp"], { motion: "qcf" }),
    category: "targetCombo",
    startup: 9,
    pattern: [8],
    recovery: 25,
    damage: 45,
    hit: { level: "mid", blockAdvantage: -14, acceptedButtons: ["A", "C"] },
    cancel: {
      tier: "mixed",
      rules: [
        { tier: "super", on: ["hit", "block"] },
        {
          tier: "branch",
          moves: ["yanosabi1", "nanase"],
          on: ["hit", "block", "whiff"],
          requiresContact: false,
          delayable: true,
        },
      ],
    },
    routeFrom: ["aragami"],
    routeTo: ["yanosabi1", "nanase"],
    knockdown: { type: "soft", techAdvantage: 21, nonTechAdvantage: 48 },
    tags: ["specialFollowup", "rekka", "aragamiTree", "softKnockdown"],
    animation: "rekkaLight",
    inputVariants: ["lp", "hp"],
  }),
  yanosabi1: authoredMove({
    name: "127 Shiki: Yanosabi",
    command: command("[Konokizu] > P", ["lp"]),
    category: "targetCombo",
    startup: 12,
    pattern: [3],
    recovery: 27,
    damage: 40,
    hit: { level: "mid", blockAdvantage: -11, acceptedButtons: ["A", "C"] },
    routeFrom: ["konokizu"],
    knockdown: { type: "hard", advantage: 38, immediateCancel: true },
    tags: ["specialFollowup", "rekka", "aragamiTree", "hardKnockdown"],
    animation: "rekkaLight",
    inputVariants: ["lp", "hp"],
  }),
  nanase: authoredMove({
    name: "125 Shiki: Nanase",
    command: command("[Konokizu] > K", ["lk"]),
    category: "targetCombo",
    startup: 12,
    pattern: [6],
    recovery: 22,
    damage: 40,
    hit: {
      level: "mid",
      blockAdvantageByRange: { close: -9, maximum: -5 },
      acceptedButtons: ["B", "D"],
      patch250: ["super cancel enabled", "hit behavior changed", "follow-up window increased", "hit/block stop increased"],
    },
    cancel: SUPER_CANCEL,
    routeFrom: ["konokizu"],
    knockdown: { type: "soft", techAdvantage: 35, nonTechAdvantage: 75, immediateCancel: true },
    tags: ["specialFollowup", "rekka", "aragamiTree", "softKnockdown", "patch250", "superCancel"],
    animation: "rekkaHeavy",
    inputVariants: ["lk", "hk"],
  }),
  yanosabi2: authoredMove({
    name: "127 Shiki: Yanosabi (Direct Branch)",
    command: command("[Aragami] > 63214P", ["lp"], { motion: "hcb" }),
    category: "targetCombo",
    startup: 24,
    pattern: [4],
    recovery: 27,
    damage: 40,
    hit: { level: "overhead", blockAdvantage: -14, acceptedButtons: ["A", "C"] },
    cancel: {
      tier: "branch",
      moves: ["kototsukiYo2", "migariUgachi"],
      on: ["hit", "block", "whiff"],
      requiresContact: false,
      delayable: true,
    },
    routeFrom: ["aragami"],
    routeTo: ["kototsukiYo2", "migariUgachi"],
    knockdown: { type: "hard", advantage: 34 },
    tags: ["specialFollowup", "rekka", "aragamiTree", "overhead", "hardKnockdown"],
    animation: "rekkaHeavy",
    inputVariants: ["lp", "hp"],
  }),
  kototsukiYo2: authoredMove({
    name: "212 Shiki: Kototsuki Yo (Yanosabi Branch)",
    command: command("[Yanosabi 2] > 63214K", ["lk"], { motion: "hcb" }),
    category: "targetCombo",
    startup: 5,
    pattern: [3],
    recovery: 33,
    damage: 90,
    damageHits: [10, 80],
    hit: { level: "mid", blockAdvantage: -17, acceptedButtons: ["B", "D"], scriptedHitgrab: true },
    routeFrom: ["yanosabi2"],
    knockdown: { type: "hard", advantage: 11 },
    tags: ["specialFollowup", "rekka", "aragamiTree", "hitgrab", "multiHit", "hardKnockdown"],
    animation: "rekkaHeavy",
    inputVariants: ["lk", "hk"],
  }),
  migariUgachi: authoredMove({
    name: "Ge Shiki: Migari Ugachi",
    command: command("[Yanosabi 2] > P", ["lp"]),
    category: "targetCombo",
    startup: 16,
    pattern: [5],
    recovery: 30,
    damage: 60,
    hit: { level: "mid", blockAdvantage: -16, acceptedButtons: ["A", "C"] },
    routeFrom: ["yanosabi2"],
    knockdown: { type: "hard", advantage: 21 },
    tags: ["specialFollowup", "rekka", "aragamiTree", "hardKnockdown"],
    animation: "rekkaLight",
    inputVariants: ["lp", "hp"],
  }),
  munotsuchi: authoredMove({
    name: "124 Shiki: Munotsuchi",
    command: command("[Aragami] > 63214K", ["lk"], { motion: "hcb" }),
    category: "targetCombo",
    startup: 21,
    pattern: [2],
    recovery: 29,
    damage: 60,
    hit: { level: "low", blockAdvantage: -12, acceptedButtons: ["B", "D"] },
    cancel: {
      tier: "branch",
      moves: ["hikigane", "tsurubeotoshi"],
      on: ["hit", "block", "whiff"],
      requiresContact: false,
      delayable: true,
    },
    routeFrom: ["aragami"],
    routeTo: ["hikigane", "tsurubeotoshi"],
    knockdown: { type: "soft", techAdvantage: 23, nonTechAdvantage: 50 },
    tags: ["specialFollowup", "rekka", "aragamiTree", "low", "softKnockdown"],
    animation: "rekkaHeavy",
    inputVariants: ["lk", "hk"],
  }),
  hikigane: authoredMove({
    name: "427 Shiki: Hikigane",
    command: command("[Munotsuchi] > K", ["lk"]),
    category: "targetCombo",
    startup: 21,
    pattern: [2],
    recovery: 25,
    damage: 60,
    hit: { level: "mid", blockAdvantage: -12, acceptedButtons: ["B", "D"] },
    routeFrom: ["munotsuchi"],
    knockdown: { type: "launch", terminal: "soft", techAdvantage: 39, nonTechAdvantage: 66 },
    juggle: { mode: "juggle", cost: 1, limit: 10 },
    tags: ["specialFollowup", "rekka", "aragamiTree", "juggle", "softKnockdown"],
    animation: "rekkaHeavy",
    inputVariants: ["lk", "hk"],
  }),
  tsurubeotoshi: authoredMove({
    name: "Ge Shiki: Tsurubeotoshi",
    command: command("[Munotsuchi] > P", ["lp"]),
    category: "targetCombo",
    startup: 21,
    pattern: [2],
    recovery: 27,
    damage: 80,
    hit: { level: "mid", blockAdvantage: -8, acceptedButtons: ["A", "C"] },
    routeFrom: ["munotsuchi"],
    knockdown: { type: "hard", advantage: 36 },
    tags: ["specialFollowup", "rekka", "aragamiTree", "hardKnockdown"],
    animation: "rekkaHeavy",
    inputVariants: ["lp", "hp"],
  }),

  // Dokugami route tree ----------------------------------------------------
  dokugami: authoredMove({
    name: "115 Shiki: Dokugami",
    command: command("236C", ["hp"], { motion: "qcf" }),
    category: "special",
    startup: 18,
    pattern: [6],
    recovery: 20,
    damage: 70,
    hit: {
      level: "mid",
      advantage: -2,
      blockAdvantage: -7,
      armor: [{ type: "midBody", start: 7, end: 11 }],
    },
    cancel: {
      tier: "mixed",
      rules: [
        { tier: "super", on: ["hit", "block"] },
        {
          tier: "branch",
          moves: ["tsumiyomi"],
          on: ["hit", "block", "whiff"],
          requiresContact: false,
          delayable: true,
        },
      ],
    },
    routeTo: ["tsumiyomi"],
    tags: ["special", "rekka", "dokugamiTree", "armor", "combo"],
    animation: "rekkaHeavy",
    strength: "heavy",
  }),
  dokugamiEx: authoredMove({
    name: "EX 115 Shiki: Dokugami",
    command: command("236AC", ["lp", "hp"], { motion: "qcf", chord: true }),
    category: "od",
    startup: 1,
    pattern: [1],
    recovery: 1,
    damage: 0,
    hit: {
      level: "mid",
      placeholderOnly: true,
      reason: "SNK marks EX available, but the current Dream Cancel frame table omits an independent 236AC row.",
    },
    cancel: {
      tier: "branch",
      moves: ["tsumiyomi"],
      on: ["hit", "block", "whiff"],
      requiresContact: false,
      delayable: true,
    },
    cost: { super: 50 },
    routeTo: ["tsumiyomi"],
    tags: ["special", "ex", "rekka", "dokugamiTree", "needsLab", "disabledUntilLab"],
    animation: "rekkaHeavy",
    dataConfidence: NEEDS_LAB,
    strength: "ex",
    needsLab: true,
    disabled: true,
  }),
  tsumiyomi: authoredMove({
    name: "401 Shiki: Tsumiyomi",
    command: command("[Dokugami] > 63214P", ["lp"], { motion: "hcb" }),
    category: "targetCombo",
    startup: 10,
    pattern: [3],
    recovery: 29,
    damage: 25,
    hit: { level: "mid", advantage: -11, blockAdvantage: -13, acceptedButtons: ["A", "C"] },
    cancel: {
      tier: "mixed",
      rules: [
        { tier: "super", on: ["hit", "block"] },
        {
          tier: "branch",
          moves: ["batsuyomi"],
          on: ["hit", "block", "whiff"],
          requiresContact: false,
          delayable: true,
        },
      ],
    },
    routeFrom: ["dokugami", "dokugamiEx"],
    routeTo: ["batsuyomi"],
    tags: ["specialFollowup", "rekka", "dokugamiTree", "superCancel"],
    animation: "rekkaHeavy",
    inputVariants: ["lp", "hp"],
  }),
  batsuyomi: authoredMove({
    name: "402 Shiki: Batsuyomi",
    command: command("[Tsumiyomi] > 6P", ["lp"], { direction: "forward" }),
    category: "targetCombo",
    startup: 14,
    pattern: [3],
    recovery: 36,
    damage: 30,
    hit: { level: "mid", blockAdvantage: -20, acceptedButtons: ["A", "C"] },
    cancel: {
      tier: "branch",
      moves: ["oniyaki2"],
      on: ["hit", "block", "whiff"],
      requiresContact: false,
      delayable: true,
    },
    routeFrom: ["tsumiyomi"],
    routeTo: ["oniyaki2"],
    knockdown: { type: "soft", techAdvantage: 26, nonTechAdvantage: 53 },
    tags: ["specialFollowup", "rekka", "dokugamiTree", "softKnockdown"],
    animation: "rekkaHeavy",
    inputVariants: ["lp", "hp"],
  }),
  oniyaki2: authoredMove({
    name: "100 Shiki: Oniyaki (Dokugami Ender)",
    command: command("[Batsuyomi] > 623P", ["lp"], { motion: "dp" }),
    category: "targetCombo",
    startup: 6,
    pattern: [4],
    recovery: 35,
    damage: 65,
    hit: { level: "mid", blockAdvantage: -20, acceptedButtons: ["A", "C"] },
    routeFrom: ["batsuyomi"],
    knockdown: { type: "soft", techAdvantage: 20, nonTechAdvantage: 47 },
    juggle: { mode: "launcher", cost: 1, limit: 10 },
    tags: ["specialFollowup", "rekka", "dokugamiTree", "dragonPunch", "softKnockdown"],
    animation: "dragonPunch",
    inputVariants: ["lp", "hp"],
  }),

  // Standalone 212 Shiki: Kototsuki Yo -----------------------------------
  kototsukiYoLight: authoredMove({
    name: "212 Shiki: Kototsuki Yo (B)",
    command: command("63214B", ["lk"], { motion: "hcb" }),
    category: "special",
    startup: 15,
    pattern: [3],
    recovery: 27,
    damage: 124,
    damageHits: [30, 10, 90],
    hit: {
      level: "mid",
      blockAdvantage: -11,
      scriptedHitgrab: true,
      startupComposition: "4+11?",
      invulnerability: [{ type: "lowBody", start: 1, end: 14 }],
    },
    cancel: SUPER_CANCEL,
    knockdown: { type: "hard", advantage: 40 },
    tags: ["special", "runGrab", "hitgrab", "multiHit", "hardKnockdown", "lowCrush"],
    animation: "rekkaHeavy",
    dataConfidence: INFERRED,
    strength: "light",
  }),
  kototsukiYoHeavy: authoredMove({
    name: "212 Shiki: Kototsuki Yo (D)",
    command: command("63214D", ["hk"], { motion: "hcb" }),
    category: "special",
    startup: 15,
    pattern: [3],
    recovery: 27,
    damage: 124,
    damageHits: [30, 10, 90],
    hit: {
      level: "mid",
      blockAdvantage: -11,
      scriptedHitgrab: true,
      startupComposition: "4+11?",
      invulnerability: [{ type: "lowBodyAfterProximityBox", start: null, end: null }],
    },
    cancel: SUPER_CANCEL,
    knockdown: { type: "hard", advantage: 40 },
    tags: ["special", "runGrab", "hitgrab", "multiHit", "hardKnockdown", "lowCrush"],
    animation: "rekkaHeavy",
    dataConfidence: INFERRED,
    strength: "heavy",
  }),
  kototsukiYoEx: authoredMove({
    name: "EX 212 Shiki: Kototsuki Yo",
    command: command("63214BD", ["lk", "hk"], { motion: "hcb", chord: true }),
    category: "od",
    startup: 3,
    pattern: [1],
    recovery: 39,
    damage: 170,
    damageHits: [50, 120],
    hit: {
      level: "throw",
      unblockable: true,
      scriptedCommandGrab: true,
      invulnerability: [{ type: "fullBody", start: 3, end: 3 }],
      patch250: ["hit behavior altered", "recovery on hit reduced"],
    },
    cost: { super: 50 },
    knockdown: { type: "hard", advantage: 59 },
    tags: ["special", "ex", "commandGrab", "unblockable", "multiHit", "hardKnockdown", "patch250"],
    animation: "throw",
    strength: "ex",
  }),

  // Super, MAX, and Climax -------------------------------------------------
  orochinagiLight: authoredMove({
    name: "Ura 108 Shiki: Orochinagi (A)",
    command: command("214236A", ["lp"], { motion: "qcbHcf", hold: true }),
    category: "super",
    startup: 23,
    pattern: [10],
    recovery: 30,
    damage: 180,
    hit: {
      level: "mid",
      blockAdvantage: -21,
      chargeStartupMax: 99,
      damageByCharge: [180, 210, 240, 270],
      invulnerability: [
        { type: "fullBody", start: 1, end: 3 },
        { type: "upperBody", start: 4, end: 18 },
        { type: "upperBody", state: "charge" },
      ],
    },
    cancel: { tier: "advanced", moves: ["max182", "yakumo"], on: ["hit", "block"] },
    cost: { super: 100 },
    routeTo: ["max182", "yakumo"],
    knockdown: { type: "hard", advantage: 58 },
    tags: ["super", "chargeable", "advancedCancel", "climaxCancel", "hardKnockdown"],
    animation: "fireballHeavy",
    strength: "light",
  }),
  orochinagiHeavy: authoredMove({
    name: "Ura 108 Shiki: Orochinagi (C)",
    command: command("214236C", ["hp"], { motion: "qcbHcf", hold: true }),
    category: "super",
    startup: 23,
    pattern: [10],
    recovery: 30,
    damage: 180,
    hit: {
      level: "mid",
      blockAdvantage: -21,
      chargeStartupMax: 99,
      damageByCharge: [180, 210, 240, 270],
      invulnerability: [
        { type: "fullBody", start: 1, end: 3 },
        { type: "upperBody", start: 4, end: 18 },
        { type: "upperBody", state: "charge" },
      ],
    },
    cancel: { tier: "advanced", moves: ["max182", "yakumo"], on: ["hit", "block"] },
    cost: { super: 100 },
    routeTo: ["max182", "yakumo"],
    knockdown: { type: "hard", advantage: 58 },
    tags: ["super", "chargeable", "advancedCancel", "climaxCancel", "hardKnockdown"],
    animation: "fireballHeavy",
    strength: "heavy",
  }),
  maxOrochinagi: authoredMove({
    name: "MAX Ura 108 Shiki: Orochinagi",
    command: command("214236AC", ["lp", "hp"], { motion: "qcbHcf", chord: true, hold: true }),
    category: "super",
    startup: 10,
    pattern: [10],
    recovery: 30,
    damage: 330,
    damageHits: [110, 110, 110],
    hit: {
      level: "mid",
      blockAdvantage: -17,
      chargeStartupMax: 104,
      damageByCharge: [330, 345, 360, 420],
      scriptedTripleHit: true,
      invulnerability: [
        { type: "fullBody", start: 1, end: 9 },
        { type: "upperBody", state: "charge" },
      ],
    },
    cancel: { tier: "climax", moves: ["yakumo"], on: ["hit", "block"] },
    cost: { super: 200 },
    routeTo: ["yakumo"],
    knockdown: { type: "hard", advantage: 62 },
    tags: ["super", "maxSuper", "chargeable", "multiHit", "climaxCancel", "hardKnockdown"],
    animation: "fireballHeavy",
    strength: "max",
  }),
  shiki182Light: authoredMove({
    name: "182 Shiki (A)",
    command: command("236236A", ["lp"], { motion: "qcfQcf", hold: true }),
    category: "super",
    startup: 13,
    pattern: [{ id: "first", frames: 2, gapAfter: 18 }, { id: "second", frames: 2 }],
    recovery: 40,
    damage: 180,
    damageHits: [80, 100],
    hit: {
      level: "mid",
      blockAdvantage: -19,
      chargeStartupMax: 130,
      damageByCharge: [180, 200, 230, 250],
      invulnerability: [{ type: "fullBody", start: 1, end: 17 }],
    },
    cancel: { tier: "advanced", moves: ["maxOrochinagi", "yakumo"], on: ["hit", "block"] },
    cost: { super: 100 },
    routeTo: ["maxOrochinagi", "yakumo"],
    knockdown: { type: "hard", advantage: 50 },
    tags: ["super", "chargeable", "multiHit", "advancedCancel", "climaxCancel", "hardKnockdown"],
    animation: "dragonPunch",
    strength: "light",
  }),
  shiki182Heavy: authoredMove({
    name: "182 Shiki (C)",
    command: command("236236C", ["hp"], { motion: "qcfQcf", hold: true }),
    category: "super",
    startup: 13,
    pattern: [{ id: "first", frames: 2, gapAfter: 18 }, { id: "second", frames: 2 }],
    recovery: 40,
    damage: 180,
    damageHits: [80, 100],
    hit: {
      level: "mid",
      blockAdvantage: -19,
      chargeStartupMax: 130,
      damageByCharge: [180, 200, 230, 250],
      invulnerability: [{ type: "fullBody", start: 1, end: 17 }],
    },
    cancel: { tier: "advanced", moves: ["maxOrochinagi", "yakumo"], on: ["hit", "block"] },
    cost: { super: 100 },
    routeTo: ["maxOrochinagi", "yakumo"],
    knockdown: { type: "hard", advantage: 50 },
    tags: ["super", "chargeable", "multiHit", "advancedCancel", "climaxCancel", "hardKnockdown"],
    animation: "dragonPunch",
    strength: "heavy",
  }),
  max182: authoredMove({
    name: "MAX 182 Shiki",
    command: command("236236AC", ["lp", "hp"], { motion: "qcfQcf", chord: true, hold: true }),
    category: "super",
    startup: 7,
    pattern: [{ id: "first", frames: 2, gapAfter: 18 }, { id: "second", frames: 2 }],
    recovery: 40,
    damage: 310,
    damageHits: [90, 100, 120],
    hit: {
      level: "mid",
      blockAdvantage: -19,
      chargeStartupMax: 127,
      damageByCharge: [310, 330, 370, 430],
      scriptedThirdImpactSharesSecondWindow: true,
      invulnerability: [{ type: "fullBody", start: 1, end: 14 }],
    },
    cancel: { tier: "climax", moves: ["yakumo"], on: ["hit", "block"] },
    cost: { super: 200 },
    routeTo: ["yakumo"],
    knockdown: { type: "hard", advantage: 62 },
    tags: ["super", "maxSuper", "chargeable", "multiHit", "climaxCancel", "hardKnockdown"],
    animation: "dragonPunch",
    strength: "max",
  }),
  yakumo: authoredMove({
    name: "Ura 1212 Shiki: Yakumo",
    command: command("214236CD", ["hp", "hk"], { motion: "qcbHcf", chord: true }),
    category: "climax",
    startup: 11,
    pattern: YAKUMO_CINEMATIC_PATTERN,
    recovery: 45,
    damage: 440,
    damageHits: [90, 60, 60, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
    hitOverrides: YAKUMO_CINEMATIC_HIT_OVERRIDES,
    hit: {
      level: "mid",
      blockAdvantageByRange: { close: -24, maximum: -5 },
      minimumComboDamage: 255,
      scriptedCinematic: true,
      invulnerability: [{ type: "fullBody", start: 1, end: 16 }],
      minimumScaling: 0.4,
    },
    cost: { super: 300 },
    knockdown: { type: "hard", advantage: 35 },
    tags: ["climax", "super", "cinematic", "multiHit", "hardKnockdown", "maxModeClimaxFinisher"],
    animation: "rekkaHeavy",
    strength: "climax",
    // Original AgentFighter resource tuning: committing Quick MAX and the
    // remaining three stocks gives this Climax a fixed 2.125x MAX-state
    // modifier. It never reads the defender's remaining health, so 1000 HP is
    // a natural TOD while an 1100 HP training dummy survives with 100.
    maxModeDamageMultiplier: 2.125,
  }),

  // Universal KOF XV systems ----------------------------------------------
  rollForward: authoredMove({
    name: "Emergency Evasion (Forward)",
    command: command("neutral/6 + A+B", ["lp", "lk"], { chord: true, direction: "forward" }),
    category: "system",
    startup: 1,
    pattern: [{ id: "evasion", frames: 24 }],
    recovery: 9,
    damage: 0,
    hit: { level: "none", disabled: true, invulnerability: [{ type: "strike+projectile", start: 1, end: 24 }], losesTo: ["throw"] },
    tags: ["system", "roll", "forward", "nonAttack", "invulnerable"],
    animation: "walk",
    dataConfidence: SYSTEM_VERIFIED,
  }),
  rollBackward: authoredMove({
    name: "Emergency Evasion (Backward)",
    command: command("4 + A+B", ["lp", "lk"], { chord: true, direction: "back" }),
    category: "system",
    startup: 1,
    pattern: [{ id: "evasion", frames: 24 }],
    recovery: 9,
    damage: 0,
    hit: { level: "none", disabled: true, invulnerability: [{ type: "strike+projectile", start: 1, end: 24 }], losesTo: ["throw"] },
    tags: ["system", "roll", "backward", "nonAttack", "invulnerable"],
    animation: "walk",
    dataConfidence: SYSTEM_VERIFIED,
  }),
  guardCancelRollForward: authoredMove({
    name: "Guard Cancel Emergency Evasion (Forward)",
    command: command("blockstun: neutral/6/3 + A+B", ["lp", "lk"], { chord: true, direction: "forward" }),
    category: "system",
    startup: 1,
    pattern: [{ id: "evasion", frames: 24 }],
    recovery: 9,
    damage: 0,
    hit: { level: "none", disabled: true, invulnerability: [{ type: "fullBody", start: 1, end: 33 }] },
    cost: { super: 100 },
    tags: ["system", "guardCancel", "roll", "forward", "nonAttack", "invulnerable"],
    animation: "walk",
    dataConfidence: SYSTEM_VERIFIED,
  }),
  guardCancelRollBackward: authoredMove({
    name: "Guard Cancel Emergency Evasion (Backward)",
    command: command("blockstun: 4/7 + A+B", ["lp", "lk"], { chord: true, direction: "back" }),
    category: "system",
    startup: 1,
    pattern: [{ id: "evasion", frames: 24 }],
    recovery: 9,
    damage: 0,
    hit: { level: "none", disabled: true, invulnerability: [{ type: "fullBody", start: 1, end: 33 }] },
    cost: { super: 100 },
    tags: ["system", "guardCancel", "roll", "backward", "nonAttack", "invulnerable"],
    animation: "walk",
    dataConfidence: SYSTEM_VERIFIED,
  }),
  guardCancelBlowback: authoredMove({
    name: "Guard Cancel Blowback",
    command: command("blockstun: C+D", ["hp", "hk"], { chord: true }),
    category: "system",
    startup: 7,
    pattern: [5],
    recovery: 27,
    damage: 5,
    hit: {
      level: "mid",
      blockAdvantage: -9,
      startupAgainstAirMove: 11,
      damageInMaxMode: 6,
      invulnerability: [{ type: "fullBody", state: "startup+active" }],
    },
    cost: { super: 100 },
    knockdown: { type: "soft" },
    juggle: { mode: "airReset", cost: 1, limit: 10 },
    tags: ["system", "guardCancel", "blowback", "reversal", "softKnockdown"],
    animation: "highHeavy",
    dataConfidence: SYSTEM_VERIFIED,
  }),
  shatterStrike: authoredMove({
    name: "Shatter Strike",
    command: command("236C+D", ["hp", "hk"], { motion: "qcf", chord: true }),
    category: "system",
    startup: 15,
    pattern: [6],
    recovery: 27,
    damage: 75,
    hit: {
      level: "mid",
      blockAdvantageByRange: { close: -10, maximum: -5 },
      armor: [{ type: "fullBodyGuardPoint", start: 4, end: 14 }],
      onGround: "crumpleToHardKnockdown",
      onAir: "wallBounce",
      refundOnHit: { super: 50 },
    },
    cost: { super: 100 },
    knockdown: { type: "crumple", terminal: "hard", advantage: 93, airHitType: "wallBounce", wallBounces: 1 },
    juggle: { mode: "crumpleOrWallBounce", cost: 1, limit: 10 },
    tags: ["system", "shatterStrike", "armor", "crumple", "wallBounce", "comboStarter"],
    animation: "highHeavy",
    dataConfidence: SYSTEM_VERIFIED,
  }),
  advanceStrike: authoredMove({
    name: "Advance Strike",
    command: command("214C+D", ["hp", "hk"], { motion: "qcb", chord: true }),
    category: "system",
    startup: 28,
    pattern: [6],
    recovery: 37,
    damage: 100,
    hit: {
      level: "mid",
      blockAdvantage: 3,
      contactRecovery: 14,
      whiffRecovery: 37,
      armor: [{ type: "fullBodyStrikeArmor", start: 7, end: 33 }],
      throwCounterWindow: { start: 4, end: 27 },
      throwCounterResult: "crumple",
      throwCounterFollowupScaling: 0.3,
      refundOnHitOrBlock: { super: 50 },
      sourceProseDiscrepancy: "Defense prose says armor F8+ / throw counter F3+; current character row says F7-33 / F4-27.",
    },
    cost: { super: 50 },
    knockdown: { type: "hard", advantage: 68, throwCounterType: "crumple", throwCounterAdvantage: 103 },
    juggle: { mode: "throwCounterCrumple", cost: 1, limit: 10 },
    tags: ["system", "advanceStrike", "armor", "throwCounter", "hardKnockdown", "plusOnBlock"],
    animation: "highHeavy",
    dataConfidence: SYSTEM_VERIFIED,
  }),
  quickMax: authoredMove({
    name: "MAX Mode (Quick)",
    command: command("normal/command hit or block: B+C", ["lk", "hp"], { chord: true }),
    category: "system",
    startup: 1,
    pattern: [{ id: "activation", frames: 1 }],
    recovery: 0,
    damage: 0,
    hit: {
      level: "none",
      disabled: true,
      stateTransition: "quickMax",
      cancelFrom: ["groundNormal", "groundCommandNormal"],
      on: ["hit", "block"],
      maxGaugeByTeamPosition: { point: 1000, middle: 1250, anchor: 1500 },
      noAttackOrGuardCrushBonus: true,
    },
    cost: { super: 200 },
    tags: ["system", "quickMax", "cancel", "nonAttack", "todCore"],
    animation: "idle",
    dataConfidence: SYSTEM_VERIFIED,
  }),
};

export const EMBER_TOD_SKELETONS = Object.freeze({
  practicalThreeBar: Object.freeze({
    evidence: "Dream Cancel Kyo combo page; 563-damage three-bar route",
    status: "community-verified-before-2.50; components remain valid in 2.51",
    route: Object.freeze([
      "crouchB",
      "crouchA",
      "shiki88Canceled",
      "quickMax",
      "closeC",
      "shiki88Canceled",
      "redKickEx",
      "kaiLight",
      "kaiFollowLight",
      "dokugami",
      "tsumiyomi",
      "yakumo",
    ]),
  }),
  fullResourceNearTodAcceptance: Object.freeze({
    evidence: "Engine acceptance skeleton derived from Kyo MAX/EX/super cancel topology",
    status: "structure-only-needs-2.51-playback-damage-validation",
    route: Object.freeze([
      "closeC",
      "shiki88Canceled",
      "quickMax",
      "closeD",
      "redKickEx",
      "kaiEx",
      "kaiHeavy",
      "kaiFollowHeavy",
      "aragami",
      "yanosabi2",
      "kototsukiYo2",
      "oniyakiHeavy",
      "orochinagiHeavy",
      "max182",
      "yakumo",
    ]),
    assertions: Object.freeze([
      "starter",
      "quickMax",
      "exGroundBounce",
      "launcher",
      "rekkaBranch",
      "juggle",
      "superCancel",
      "advancedCancel",
      "climaxCancel",
    ]),
  }),
  stunTodReference: Object.freeze({
    evidence: "playergodaines Kyo Stun + ToD video, game version 2.41",
    status: "historical-reference-needs-2.51-revalidation",
    route: Object.freeze([
      "closeC",
      "shiki88Canceled",
      "quickMax",
      "redKickEx",
      "kaiEx",
      "dokugami",
      "tsumiyomi",
      "batsuyomi",
      "oniyaki2",
      "orochinagiHeavy",
      "max182",
      "yakumo",
    ]),
    requiresStunReset: true,
  }),
});

export const EMBER_ROSTER_METADATA = Object.freeze({
  buttonMapping: Object.freeze({ A: "lp", B: "lk", C: "hp", D: "hk" }),
  hasGroundThrows: true,
  hasAirThrow: false,
  jumpDataRule: "vertical hop shares h.*; vertical normal/hyper jump shares j.* until direct game extraction proves a distinct row",
  exCost: 50,
  superCost: 100,
  maxSuperCost: 200,
  climaxCost: 300,
});

export const EMBER_MOVESET = defineMoveset({
  id: "ember",
  name: "Ember",
  archetype: "KOF-style rushdown / rekka pressure",
  controlLayout: "kofFourButtonOnSixButtonSchema",
  resourceModel: "ember",
  aliases: {
    highLight: "closeA",
    highHeavy: "closeC",
    midLight: "farA",
    midHeavy: "farC",
    lowLight: "crouchB",
    lowHeavy: "sweep",
    rekkaLight: "aragami",
    rekkaHeavy: "dokugami",
    dragonPunch: "oniyakiHeavy",
    airLight: "jumpA",
    airHeavy: "jumpD",
    airHammer: "narakuOtoshi",
    throw: "hatsugane",
    verticalHopA: "hopA",
    verticalHopB: "hopB",
    verticalHopC: "hopC",
    verticalHopD: "hopD",
    verticalJumpA: "jumpA",
    verticalJumpB: "jumpB",
    verticalJumpC: "jumpC",
    verticalJumpD: "jumpD",
    roll: "rollForward",
    gcRoll: "guardCancelRollForward",
    blowback: "blowbackGround",
    gcBlowback: "guardCancelBlowback",
  },
  moves,
});

export default EMBER_MOVESET;
