import { defineMoveset } from "../move-data.js";

// Frame values use the live Capcom Ryu table checked on 2026-07-21.  Community
// measurements are used only where Capcom exposes a coarse span (multi-hit gaps,
// juggle values, landing recovery, and conditional branches).
const DATA_REVISION = "capcom-live-2026-07-21+ryu-2026-03-17";

const W = (id, start, end = start, hitId = id) => ({ id, start, end, hitId });
const H = (id, start, end, damage, extra = {}) => ({ id, start, end, damage, ...extra });
const ADV = (advantage = null, extra = {}) => ({ advantage, ...extra });
const KD = (type = "none", extra = {}) => ({ type, ...extra });
const J = (start = 0, increase = 0, limit = 0, extra = {}) => ({ start, increase, limit, ...extra });
const CMD = (label, buttons = [], extra = {}) => ({ label, buttons, ...extra });

const FREE = Object.freeze({ cost: { super: 0, drive: 0 }, conditions: [] });
const NO_CANCEL = Object.freeze({ type: "none", into: [], windows: [] });
const NO_KNOCKDOWN = Object.freeze(KD());
const NO_JUGGLE = Object.freeze(J());

const resource = (cost = {}, extra = {}) => ({
  cost: { super: cost.super ?? 0, drive: cost.drive ?? 0, guard: cost.guard ?? 0 },
  conditions: [],
  ...extra,
});

const cancelWindow = (start, end, into, extra = {}) => ({
  start,
  end,
  on: ["hit", "block"],
  into: Array.isArray(into) ? into : [into],
  ...extra,
});

const cancel = (type, windows, extra = {}) => ({
  type,
  into: [...new Set(windows.flatMap((window) => window.into ?? []))],
  windows,
  ...extra,
});

const C_INTO = ["special", "od", "driveImpact", "driveRushCancel", "super"];
const SA2_INTO = ["super2", "super3", "criticalArt"];
const SA3_INTO = ["super3", "criticalArt"];

function authoredMove({
  id,
  name,
  category,
  command,
  startup,
  activeWindows,
  recovery,
  damage = 0,
  hitLevel = "high",
  hit = ADV(),
  block = ADV(),
  cancel: cancelProfile = NO_CANCEL,
  resource: resourceProfile = FREE,
  knockdown = NO_KNOCKDOWN,
  juggle = NO_JUGGLE,
  tags = [],
  animation,
  hits,
  ...extra
}) {
  const windows = activeWindows.map((window) => ({ ...window }));
  const authoredHits = hits ?? windows.map((window) => H(
    window.hitId,
    window.start,
    window.end,
    damage,
    { hitLevel },
  ));
  return {
    id,
    name,
    category,
    command,
    startup,
    activeWindows: windows,
    recovery,
    damage,
    hit,
    block,
    cancel: cancelProfile,
    cancels: cancelProfile.windows,
    resource: resourceProfile,
    resourceCost: { ...resourceProfile.cost },
    resourceLabel: resourceProfile.label ?? "",
    knockdown,
    knockdownType: knockdown.type === "none" ? undefined : knockdown.type,
    juggle,
    juggleCost: Number.isFinite(juggle.increase) ? juggle.increase : 0,
    juggleLimit: Number.isFinite(juggle.limit) ? juggle.limit : 0,
    tags: [category, ...tags],
    animation,
    hitLevel,
    hits: authoredHits,
    dataRevision: DATA_REVISION,
    ...extra,
  };
}

const MOVES = [
  // Standing normals -------------------------------------------------------
  authoredMove({
    id: "standLightPunch", name: "Standing Light Punch", category: "normal",
    command: CMD("5LP", ["lp"], { direction: "neutral" }),
    startup: 4, activeWindows: [W("jab", 4, 6)], recovery: 7, damage: 300,
    hit: ADV(4), block: ADV(-1),
    cancel: cancel("C+chain", [
      cancelWindow(4, 6, C_INTO),
      cancelWindow(4, 6, ["normal"], { moves: ["standLightPunch", "crouchLightPunch", "crouchLightKick"] }),
    ]),
    juggle: J(1, 1, 0), tags: ["standing", "punch", "light", "rapidCancel"], animation: "highLight",
  }),
  authoredMove({
    id: "standMediumPunch", name: "Standing Medium Punch", category: "normal",
    command: CMD("5MP", ["mp"], { direction: "neutral" }),
    startup: 6, activeWindows: [W("main", 6, 9)], recovery: 11, damage: 600,
    hit: ADV(7), block: ADV(-1),
    cancel: cancel("C+target", [
      cancelWindow(6, 9, C_INTO),
      cancelWindow(6, 9, ["targetCombo"], { moves: ["fuwaSecond"] }),
    ]),
    juggle: J(1, 1, 0), tags: ["standing", "punch", "medium"], animation: "highHeavy",
    whiffRecovery: 13,
  }),
  authoredMove({
    id: "standHeavyPunch", name: "Standing Heavy Punch", category: "normal",
    command: CMD("5HP", ["hp"], { direction: "neutral" }),
    startup: 10, activeWindows: [W("main", 10, 14)], recovery: 18, damage: 800,
    hit: ADV(4, { forceStand: true }), block: ADV(-2),
    cancel: cancel("C+target", [
      cancelWindow(10, 14, C_INTO),
      cancelWindow(10, 14, ["targetCombo"], { moves: ["highDoubleStrike"] }),
    ]),
    juggle: J(1, 1, 0), tags: ["standing", "punch", "heavy", "forceStand"], animation: "highHeavy",
  }),
  authoredMove({
    id: "standLightKick", name: "Standing Light Kick", category: "normal",
    command: CMD("5LK", ["lk"], { direction: "neutral" }),
    startup: 5, activeWindows: [W("main", 5, 7)], recovery: 11, damage: 300,
    hit: ADV(2), block: ADV(-4),
    cancel: cancel("C", [
      cancelWindow(5, 7, ["special", "od", "driveImpact", "super"]),
      cancelWindow(7, 7, ["driveRushCancel"]),
    ]),
    juggle: J(1, 1, 0), tags: ["standing", "kick", "light"], animation: "highLight",
  }),
  authoredMove({
    id: "standMediumKick", name: "Standing Medium Kick", category: "normal",
    command: CMD("5MK", ["mk"], { direction: "neutral" }),
    startup: 9, activeWindows: [W("main", 9, 11)], recovery: 18, damage: 700,
    hit: ADV(4), block: ADV(-4), juggle: J(1, 1, 0),
    tags: ["standing", "kick", "medium", "poke", "lowAvoidanceF4to11"], animation: "highHeavy",
  }),
  authoredMove({
    id: "standHeavyKick", name: "Standing Heavy Kick", category: "normal",
    command: CMD("5HK", ["hk"], { direction: "neutral" }),
    startup: 12, activeWindows: [W("main", 12, 15)], recovery: 20, damage: 900,
    hit: ADV(9, { airborne: "limitedJuggle", punishCounter: "crumple36F" }), block: ADV(1),
    juggle: J(1, 1, 0, { punishCounterGroundStart: -1 }),
    tags: ["standing", "kick", "heavy", "whiffsOnCrouch", "airJuggle", "punishCrumple"], animation: "highHeavy",
    blockRecovery: 22,
  }),

  // Crouching normals ------------------------------------------------------
  authoredMove({
    id: "crouchLightPunch", name: "Crouching Light Punch", category: "normal",
    command: CMD("2LP", ["lp"], { direction: "down" }),
    startup: 4, activeWindows: [W("jab", 4, 5)], recovery: 9, damage: 300,
    hit: ADV(4), block: ADV(-1),
    cancel: cancel("C+chain", [
      cancelWindow(4, 5, C_INTO),
      cancelWindow(4, 5, ["normal"], { moves: ["standLightPunch", "crouchLightPunch", "crouchLightKick"] }),
    ]),
    juggle: J(1, 1, 0), tags: ["crouching", "punch", "light", "rapidCancel"], animation: "lowLight",
  }),
  authoredMove({
    id: "crouchMediumPunch", name: "Crouching Medium Punch", category: "normal",
    command: CMD("2MP", ["mp"], { direction: "down" }),
    startup: 6, activeWindows: [W("main", 6, 9)], recovery: 13, damage: 600,
    hit: ADV(5), block: ADV(0), cancel: cancel("C", [cancelWindow(6, 9, C_INTO)]),
    juggle: J(1, 1, 0), tags: ["crouching", "punch", "medium"], animation: "lowHeavy",
    whiffRecovery: 15,
  }),
  authoredMove({
    id: "crouchHeavyPunch", name: "Crouching Heavy Punch", category: "normal",
    command: CMD("2HP", ["hp"], { direction: "down" }),
    startup: 9, activeWindows: [W("main", 9, 14)], recovery: 22, damage: 800,
    hit: ADV(1, { forceStand: true }), block: ADV(-7),
    cancel: cancel("C-first-active-only", [cancelWindow(9, 9, C_INTO)]),
    juggle: J(1, 1, 0), tags: ["crouching", "punch", "heavy", "antiAir", "forceStand"], animation: "lowHeavy",
    antiAirInvulnerability: [{ frame: 9, area: "fist" }, { start: 10, end: 14, area: "head" }],
  }),
  authoredMove({
    id: "crouchLightKick", name: "Crouching Light Kick", category: "normal",
    command: CMD("2LK", ["lk"], { direction: "down" }),
    startup: 5, activeWindows: [W("main", 5, 6)], recovery: 10, damage: 200, hitLevel: "low",
    hit: ADV(3), block: ADV(-1),
    cancel: cancel("chain", [cancelWindow(5, 6, ["normal"], {
      moves: ["standLightPunch", "crouchLightPunch", "crouchLightKick"],
    })]),
    juggle: J(1, 1, 0), tags: ["crouching", "kick", "light", "low", "rapidCancel"], animation: "lowLight",
  }),
  authoredMove({
    id: "crouchMediumKick", name: "Crouching Medium Kick", category: "normal",
    command: CMD("2MK", ["mk"], { direction: "down" }),
    startup: 8, activeWindows: [W("main", 8, 10)], recovery: 19, damage: 500, hitLevel: "low",
    hit: ADV(1), block: ADV(-6), cancel: cancel("C", [cancelWindow(8, 10, C_INTO)]),
    juggle: J(1, 1, 0), tags: ["crouching", "kick", "medium", "low", "starterScale20"], animation: "lowHeavy",
    initialProration: 0.8,
  }),
  authoredMove({
    id: "crouchHeavyKick", name: "Low Spinning Sweep", category: "normal",
    command: CMD("2HK", ["hk"], { direction: "down" }),
    startup: 9, activeWindows: [W("sweep", 9, 11)], recovery: 23, damage: 900, hitLevel: "low",
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 40 }), block: ADV(-12),
    knockdown: KD("normal", { advantage: 40, punishCounter: "extendedHardKnockdown" }),
    juggle: J(1, 1, 5), tags: ["crouching", "kick", "heavy", "low", "sweep", "punishHardKnockdown"], animation: "lowHeavy",
    blockRecovery: 29,
  }),

  // Jumping normals --------------------------------------------------------
  authoredMove({
    id: "jumpLightPunch", name: "Jumping Light Punch", category: "normal",
    command: CMD("j.LP", ["lp"], { direction: "up", air: true }),
    startup: 4, activeWindows: [W("main", 4, 13)], recovery: 0, landingRecovery: 3, damage: 300, hitLevel: "overhead",
    hit: ADV(4, { best: 9, landingDependent: true }), block: ADV(0, { best: 5, landingDependent: true }),
    juggle: J(1, 1, 0), tags: ["air", "punch", "light", "overhead", "fuzzy"], animation: "airLight",
  }),
  authoredMove({
    id: "jumpMediumPunch", name: "Jumping Medium Punch", category: "normal",
    command: CMD("j.MP", ["mp"], { direction: "up", air: true }),
    startup: 8, activeWindows: [W("first", 8, 9), W("second", 10, 12)], recovery: 0, landingRecovery: 3,
    damage: 700, hitLevel: "overhead",
    hits: [
      H("first", 8, 9, 350, { hitLevel: "overhead", juggleCost: 1, juggleLimit: 6 }),
      H("second", 10, 12, 350, { hitLevel: "overhead", juggleCost: 1, juggleLimit: 7 }),
    ],
    hit: ADV(10, { best: 13, landingDependent: true, airborne: "limitedJuggle" }),
    block: ADV(6, { best: 9, landingDependent: true, secondOverheadRequiresFirstWhiff: true }),
    cancel: cancel("air-special", [cancelWindow(8, 12, ["special", "od"], { moves: ["airTatsu", "airTatsuOD"] })]),
    juggle: J([1, 1], [1, 1], [6, 7]), tags: ["air", "punch", "medium", "multiHit", "overhead", "airJuggle"], animation: "airHeavy",
  }),
  authoredMove({
    id: "jumpHeavyPunch", name: "Jumping Heavy Punch", category: "normal",
    command: CMD("j.HP", ["hp"], { direction: "up", air: true }),
    startup: 9, activeWindows: [W("main", 9, 14)], recovery: 0, landingRecovery: 3, damage: 800, hitLevel: "overhead",
    hit: ADV(8, { best: 15, landingDependent: true, counterAir: "slamKnockdown" }),
    block: ADV(4, { best: 11, landingDependent: true }), juggle: J(1, 0, 0),
    tags: ["air", "punch", "heavy", "overhead", "counterAirSlam"], animation: "airHeavy",
  }),
  authoredMove({
    id: "jumpLightKick", name: "Jumping Light Kick", category: "normal",
    command: CMD("j.LK", ["lk"], { direction: "up", air: true }),
    startup: 6, activeWindows: [W("main", 6, 15)], recovery: 0, landingRecovery: 3, damage: 300, hitLevel: "overhead",
    hit: ADV(5, { best: 10, landingDependent: true }), block: ADV(1, { best: 6, landingDependent: true }),
    juggle: J(1, 1, 0), tags: ["air", "kick", "light", "overhead", "crossUp"], animation: "airLight",
  }),
  authoredMove({
    id: "jumpMediumKick", name: "Jumping Medium Kick", category: "normal",
    command: CMD("j.MK", ["mk"], { direction: "up", air: true }),
    startup: 7, activeWindows: [W("main", 7, 12)], recovery: 0, landingRecovery: 3, damage: 500, hitLevel: "overhead",
    hit: ADV(8, { best: 13, landingDependent: true }), block: ADV(4, { best: 9, landingDependent: true }),
    juggle: J(1, 1, 0), tags: ["air", "kick", "medium", "overhead", "crossUp"], animation: "airHeavy",
  }),
  authoredMove({
    id: "jumpHeavyKick", name: "Jumping Heavy Kick", category: "normal",
    command: CMD("j.HK", ["hk"], { direction: "up", air: true }),
    startup: 10, activeWindows: [W("main", 10, 17)], recovery: 0, landingRecovery: 3, damage: 800, hitLevel: "overhead",
    hit: ADV(9, { best: 15, landingDependent: true }), block: ADV(5, { best: 11, landingDependent: true }),
    juggle: J(1, 0, 0), tags: ["air", "kick", "heavy", "overhead", "jumpIn"], animation: "airHeavy",
  }),

  // Unique attacks and target-combo continuations -------------------------
  authoredMove({
    id: "collarboneBreaker", name: "Collarbone Breaker", category: "commandNormal",
    command: CMD("6MP", ["mp"], { direction: "forward" }),
    startup: 20, activeWindows: [W("first", 20, 20), W("second", 21, 23)], recovery: 19, damage: 600,
    hits: [
      H("first", 20, 20, 300, { hitLevel: "high", juggleCost: 1, juggleLimit: 0 }),
      H("second", 21, 23, 300, { hitLevel: "overhead", overheadOnlyIfFirstWhiffs: true, juggleCost: 1, juggleLimit: 0 }),
    ],
    hitLevel: "overhead", hit: ADV(3), block: ADV(-3), juggle: J(1, [1, 1], [0, 0]),
    tags: ["forward", "punch", "medium", "multiHit", "conditionalOverhead"], animation: "midLight",
  }),
  authoredMove({
    id: "solarPlexusStrike", name: "Solar Plexus Strike", category: "commandNormal",
    command: CMD("6HP", ["hp"], { direction: "forward" }),
    startup: 20, activeWindows: [W("first", 20, 21), W("second", 22, 24)], recovery: 16, damage: 800,
    hits: [
      H("first", 20, 21, 400, { hitLevel: "high", juggleCost: 0, juggleLimit: 0, freeJuggleForSecond: true }),
      H("second", 22, 24, 400, { hitLevel: "high", juggleCost: 1, juggleLimit: 0 }),
    ],
    hit: ADV(6), block: ADV(3), juggle: J([0, 1], [0, 1], [0, 0]),
    tags: ["forward", "punch", "heavy", "multiHit", "advancing", "plusOnBlock"], animation: "midHeavy",
  }),
  authoredMove({
    id: "shortUppercut", name: "Short Uppercut", category: "commandNormal",
    command: CMD("4HP", ["hp"], { direction: "back" }),
    startup: 7, activeWindows: [W("main", 7, 10)], recovery: 26, damage: 800,
    hit: ADV(1, { forceStand: true }), block: ADV(-13),
    cancel: cancel("C-first-active-only", [cancelWindow(7, 7, C_INTO)]), juggle: J(1, 1, 0),
    tags: ["back", "punch", "heavy", "forceStand", "firstActiveCancelOnly"], animation: "highHeavy",
  }),
  authoredMove({
    id: "axeKick", name: "Axe Kick", category: "commandNormal",
    command: CMD("4HK", ["hk"], { direction: "back" }),
    startup: 10, activeWindows: [W("first", 10, 14), W("second", 20, 22)], recovery: 21, totalFrames: 43,
    damage: 800,
    hits: [
      H("first", 10, 14, 400, { hitLevel: "high", forceStand: true, juggleCost: 1, juggleLimit: 0 }),
      H("second", 20, 22, 400, { hitLevel: "high", knockdownType: "groundBounceOTG", groundBounces: 1, juggleCost: 4, juggleLimit: 3 }),
    ],
    hit: ADV(0, { second: "groundBounceOTG" }), block: ADV(-4),
    cancel: cancel("C-both-hits", [cancelWindow(10, 14, C_INTO), cancelWindow(20, 22, C_INTO)]),
    knockdown: KD("conditional", { secondHit: "groundBounceOTG" }), juggle: J([1, 1], [1, 4], [0, 3]),
    tags: ["back", "kick", "heavy", "multiHit", "forceStand", "groundBounce", "otg"], animation: "midHeavy",
    officialActiveSpan: { start: 10, end: 23, note: "community windows end one frame earlier" },
  }),
  authoredMove({
    id: "whirlwindKick", name: "Whirlwind Kick", category: "commandNormal",
    command: CMD("6HK", ["hk"], { direction: "forward" }),
    startup: 16, activeWindows: [W("main", 16, 19)], recovery: 20, damage: 800,
    hit: ADV(2, { airborne: "limitedJuggle" }), block: ADV(-4),
    cancel: cancel("specified-air-tatsu-only", [cancelWindow(16, 19, ["special", "od"], {
      moves: ["whirlwindAirTatsu", "whirlwindAirTatsuOD"],
    })]),
    juggle: J(1, 1, 1), tags: ["forward", "kick", "heavy", "lowCrushF13to20", "airJuggle"], animation: "midHeavy",
  }),
  authoredMove({
    id: "highDoubleStrike", name: "High Double Strike", category: "targetCombo",
    command: CMD("5HP~HK", ["hk"], { direction: "neutral" }), followupFrom: "standHeavyPunch",
    startup: 9, activeWindows: [W("finisher", 9, 12)], recovery: 20, damage: 1000,
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 39 }), block: ADV(-8, { crouchBlock: -18 }),
    cancel: cancel("denjin-on-hit", [cancelWindow(9, 12, ["special"], {
      on: ["hit"], moves: ["denjinCharge"], requiresContact: true,
    })]),
    knockdown: KD("normal", { advantage: 39 }), juggle: J(1, 0, 1),
    tags: ["target", "heavy", "knockdown", "denjinFollowup", "cornerJuggle20260317"], animation: "highHeavy",
    cornerFollowups: ["shoryukenMedium", "shoryukenOD", "superArt3", "criticalArt"],
  }),
  authoredMove({
    id: "fuwaSecond", name: "Fuwa Triple Strike 1", category: "targetCombo",
    command: CMD("5MP~LK", ["lk"], { direction: "neutral" }), followupFrom: "standMediumPunch",
    startup: 5, activeWindows: [W("second", 5, 7)], recovery: 16, damage: 300,
    hit: ADV(1), block: ADV(-4),
    cancel: cancel("target-only", [cancelWindow(5, 7, ["targetCombo"], { moves: ["fuwaFinisher"] })]),
    juggle: J(1, 1, 0), tags: ["target", "light", "kick"], animation: "highLight",
  }),
  authoredMove({
    id: "fuwaFinisher", name: "Fuwa Triple Strike 2", category: "targetCombo",
    command: CMD("5MP~LK~HK", ["hk"], { direction: "neutral" }), followupFrom: "fuwaSecond",
    startup: 17, activeWindows: [W("finisher", 17, 20)], recovery: 20, damage: 900,
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 36 }), block: ADV(-8, { gapBeforeHit: 6 }),
    cancel: cancel("denjin-on-hit", [cancelWindow(17, 20, ["special"], {
      on: ["hit"], moves: ["denjinCharge"], requiresContact: true,
    })]),
    knockdown: KD("normal", { advantage: 36 }), juggle: J(1, 1, 0),
    tags: ["target", "heavy", "kick", "knockdown", "denjinFollowup"], animation: "highHeavy",
  }),

  // Ground throws ----------------------------------------------------------
  authoredMove({
    id: "shoulderThrow", name: "Shoulder Throw", category: "throw",
    command: CMD("5/6+LP+LK", ["lp", "lk"], { chord: true, direction: "neutralOrForward" }),
    startup: 5, activeWindows: [W("throw", 5, 7)], recovery: 23, damage: 1200, hitLevel: "throw",
    hit: ADV(null, { state: "hardKnockdown", knockdownAdvantage: 17, punishCounterDamage: 2040 }), block: ADV(null, { throwTechable: true }),
    knockdown: KD("hard", { advantage: 17 }), juggle: J(),
    tags: ["groundThrow", "hardKnockdown", "punishDamage2040"], animation: "throw",
  }),
  authoredMove({
    id: "somersaultThrow", name: "Somersault Throw", category: "throw",
    command: CMD("4+LP+LK", ["lp", "lk"], { chord: true, direction: "back" }),
    startup: 5, activeWindows: [W("throw", 5, 7)], recovery: 23, damage: 1200, hitLevel: "throw",
    hit: ADV(null, { state: "hardKnockdown", knockdownAdvantage: 11, punishCounterDamage: 2040, sideSwitch: true }), block: ADV(null, { throwTechable: true }),
    knockdown: KD("hard", { advantage: 11, sideSwitch: true }), juggle: J(),
    tags: ["groundThrow", "hardKnockdown", "sideSwitch", "punishDamage2040"], animation: "throw",
  }),

  // Hadoken family ---------------------------------------------------------
  authoredMove({
    id: "hadokenLight", name: "Light Hadoken", category: "special",
    command: CMD("236LP", ["lp"], { motion: "qcf" }),
    startup: 16, activeWindows: [W("projectile", 16)], recovery: 31, totalFrames: 47, damage: 700,
    hit: ADV(2), block: ADV(-5), cancel: cancel("SA3", [cancelWindow(16, 16, SA3_INTO)]),
    juggle: J("1 air", 1, 1), tags: ["projectile", "punch", "light", "singleHit"], animation: "fireballLight",
    projectile: { speedClass: "slow", hits: 1, clashHits: 1, localActive: false },
  }),
  authoredMove({
    id: "hadokenMedium", name: "Medium Hadoken", category: "special",
    command: CMD("236MP", ["mp"], { motion: "qcf" }),
    startup: 14, activeWindows: [W("projectile", 14)], recovery: 33, totalFrames: 47, damage: 700,
    hit: ADV(0), block: ADV(-7), cancel: cancel("SA3", [cancelWindow(14, 14, SA3_INTO)]),
    juggle: J("1 air", 1, 1), tags: ["projectile", "punch", "medium", "singleHit"], animation: "fireballLight",
    projectile: { speedClass: "medium", hits: 1, clashHits: 1, localActive: false },
  }),
  authoredMove({
    id: "hadokenHeavy", name: "Heavy Hadoken", category: "special",
    command: CMD("236HP", ["hp"], { motion: "qcf" }),
    startup: 12, activeWindows: [W("projectile", 12)], recovery: 35, totalFrames: 47, damage: 700,
    hit: ADV(-2), block: ADV(-9), cancel: cancel("SA3", [cancelWindow(12, 12, SA3_INTO)]),
    juggle: J("1 air", 1, 1), tags: ["projectile", "punch", "heavy", "singleHit"], animation: "fireballHeavy",
    projectile: { speedClass: "fast", hits: 1, clashHits: 1, localActive: false },
  }),
  authoredMove({
    id: "hadokenDenjin", name: "Denjin Hadoken", category: "special",
    command: CMD("236P (Denjin)", ["hp"], { motion: "qcf" }),
    startup: 12, activeWindows: [W("first", 12), W("second", 12)], recovery: 28, totalFrames: 40, damage: 1000,
    hits: [
      H("first", 12, 12, 500, { hitLevel: "high", juggleCost: 1, juggleLimit: 1 }),
      H("second", 12, 12, 500, { hitLevel: "high", juggleCost: 2, juggleLimit: 6, knockdownType: "normal" }),
    ],
    hit: ADV(null, { state: "knockdown" }), block: ADV(-1),
    cancel: cancel("SA3", [cancelWindow(12, 12, SA3_INTO)]),
    resource: resource({}, { consumes: { denjin: 1 }, conditions: ["denjinStock>=1"], label: "Denjin ×1" }),
    knockdown: KD("normal"), juggle: J(1, [1, 2], [1, 6]),
    tags: ["projectile", "denjin", "multiHit", "knockdown"], animation: "fireballHeavy",
    projectile: { speedClass: "fast", hits: 2, clashHits: 2, localActive: false },
  }),
  authoredMove({
    id: "hadokenOD", name: "Overdrive Hadoken", category: "od",
    command: CMD("236PP", ["lp", "mp"], { motion: "qcf", chord: true }), inputAlternatives: ["LP+MP", "LP+HP", "MP+HP"],
    startup: 12, activeWindows: [W("first", 12), W("second", 12)], recovery: 28, totalFrames: 40, damage: 1000,
    hits: [
      H("first", 12, 12, 500, { hitLevel: "high", juggleCost: 1, juggleLimit: 1 }),
      H("second", 12, 12, 500, { hitLevel: "high", juggleCost: 2, juggleLimit: 6, knockdownType: "normal" }),
    ],
    hit: ADV(null, { state: "knockdown" }), block: ADV(-1),
    cancel: cancel("SA2", [cancelWindow(12, 12, SA2_INTO)]),
    resource: resource({ drive: 200 }, { label: "2 Drive" }), knockdown: KD("normal"),
    juggle: J(1, [1, 2], [1, 6]), tags: ["projectile", "od", "multiHit", "knockdown"], animation: "fireballHeavy",
    projectile: { speedClass: "fast", hits: 2, clashHits: 2, localActive: false },
  }),
  authoredMove({
    id: "hadokenODDenjin", name: "Denjin Overdrive Hadoken", category: "od",
    command: CMD("236PP (Denjin)", ["lp", "mp"], { motion: "qcf", chord: true }), inputAlternatives: ["LP+MP", "LP+HP", "MP+HP"],
    startup: 12, activeWindows: [W("first", 12), W("second", 12), W("third", 12)], recovery: 26, totalFrames: 38, damage: 1200,
    hits: [
      H("first", 12, 12, 400, { hitLevel: "high", juggleCost: 1, juggleLimit: 3 }),
      H("second", 12, 12, 400, { hitLevel: "high", juggleCost: 1, juggleLimit: 3 }),
      H("third", 12, 12, 400, { hitLevel: "high", juggleCost: 1, juggleLimit: 6, knockdownType: "normal" }),
    ],
    hit: ADV(null, { state: "knockdown" }), block: ADV(2),
    cancel: cancel("SA2", [cancelWindow(12, 12, SA2_INTO)]),
    resource: resource({ drive: 200 }, { consumes: { denjin: 1 }, conditions: ["denjinStock>=1"], label: "2 Drive + Denjin ×1" }),
    knockdown: KD("normal"), juggle: J(1, [1, 1, 1], [3, 3, 6]),
    tags: ["projectile", "od", "denjin", "multiHit", "knockdown"], animation: "fireballHeavy",
    projectile: { speedClass: "fast", hits: 3, clashHits: 3, localActive: false },
  }),

  // Shoryuken family -------------------------------------------------------
  authoredMove({
    id: "shoryukenLight", name: "Light Shoryuken", category: "special",
    command: CMD("623LP", ["lp"], { motion: "dp" }),
    startup: 5, activeWindows: [W("uppercut", 5, 14)], recovery: 21, landingRecovery: 12, totalFrames: 47, damage: 1100,
    hits: [H("uppercut", 5, 14, 1100, { hitLevel: "high", lateDamage: 800, lateWindow: { start: 8, end: 14 }, knockdownType: "normal", juggleCost: 1, juggleLimit: [5, 7] })],
    hit: ADV(null, { state: "knockdown" }), block: ADV(-23),
    cancel: cancel("SA3", [cancelWindow(5, 14, SA3_INTO)]), knockdown: KD("normal"), juggle: J(1, 1, [5, 7]),
    tags: ["dragonPunch", "antiAir", "light", "lateDamage800", "airborneF7to34"], animation: "dragonPunch",
    invulnerability: [{ start: 1, end: 14, type: "antiAir" }],
  }),
  authoredMove({
    id: "shoryukenMedium", name: "Medium Shoryuken", category: "special",
    command: CMD("623MP", ["mp"], { motion: "dp" }),
    startup: 6, activeWindows: [W("uppercut", 6, 15)], recovery: 30, landingRecovery: 12, totalFrames: 57, damage: 1200,
    hits: [H("uppercut", 6, 15, 1200, { hitLevel: "high", lateDamage: 800, lateWindow: { start: 9, end: 15 }, knockdownType: "normal", juggleCost: 1, juggleLimit: [5, 7] })],
    hit: ADV(null, { state: "knockdown" }), block: ADV(-32),
    cancel: cancel("SA3", [cancelWindow(6, 15, SA3_INTO)]), knockdown: KD("normal"), juggle: J(1, 1, [5, 7]),
    tags: ["dragonPunch", "antiAir", "medium", "lateDamage800", "airborneF8to44"], animation: "dragonPunch",
    invulnerability: [{ start: 1, end: 9, type: "antiAir" }],
  }),
  authoredMove({
    id: "shoryukenHeavy", name: "Heavy Shoryuken", category: "special",
    command: CMD("623HP", ["hp"], { motion: "dp" }),
    startup: 7, activeWindows: [W("uppercut", 7, 16)], recovery: 34, landingRecovery: 12, totalFrames: 62, damage: 1400,
    hits: [H("uppercut", 7, 16, 1400, { hitLevel: "high", lateDamage: 800, lateWindow: { start: 9, end: 16 }, knockdownType: "normal", juggleCost: 1, juggleLimit: [5, 7] })],
    hit: ADV(null, { state: "knockdown" }), block: ADV(-36),
    cancel: cancel("SA3", [cancelWindow(7, 16, SA3_INTO)]), knockdown: KD("normal"), juggle: J(1, 1, [5, 7]),
    tags: ["dragonPunch", "antiAir", "heavy", "lateDamage800", "airborneF9to49"], animation: "dragonPunch",
    invulnerability: [{ start: 1, end: 8, type: "antiAir" }],
  }),
  authoredMove({
    id: "shoryukenOD", name: "Overdrive Shoryuken", category: "od",
    command: CMD("623PP", ["lp", "mp"], { motion: "dp", chord: true }), inputAlternatives: ["LP+MP", "LP+HP", "MP+HP"],
    startup: 6, activeWindows: [W("first", 6, 7), W("second", 8, 15)], recovery: 37, landingRecovery: 15, totalFrames: 67,
    damage: 1600,
    hits: [
      H("first", 6, 7, 800, { hitLevel: "high", juggleCost: 1, juggleLimit: 6 }),
      H("second", 8, 15, 800, { hitLevel: "high", knockdownType: "normal", juggleCost: 1, juggleLimit: 7 }),
    ],
    hit: ADV(null, { state: "knockdown" }), block: ADV(-40), resource: resource({ drive: 200 }, { label: "2 Drive" }),
    knockdown: KD("normal"), juggle: J([1, 1], [1, 1], [6, 7]),
    tags: ["dragonPunch", "od", "reversal", "multiHit", "airborneF8to51"], animation: "dragonPunch",
    invulnerability: [{ start: 1, end: 8, type: "full" }],
  }),

  // Ground Tatsumaki -------------------------------------------------------
  authoredMove({
    id: "tatsuLight", name: "Light Tatsumaki Senpu-kyaku", category: "special",
    command: CMD("214LK", ["lk"], { motion: "qcb" }),
    startup: 12, activeWindows: [W("spin", 12, 14)], recovery: 14, landingRecovery: 18, totalFrames: 46, damage: 900,
    hit: ADV(null, { state: "knockdown" }), block: ADV(-15), knockdown: KD("normal"), juggle: J(4, 4, 3),
    tags: ["tatsu", "light", "singleHit", "hitsCrouch", "airborne"], animation: "airTatsu",
  }),
  authoredMove({
    id: "tatsuMedium", name: "Medium Tatsumaki Senpu-kyaku", category: "special",
    command: CMD("214MK", ["mk"], { motion: "qcb" }),
    startup: 14, activeWindows: [W("first", 14, 15), W("second", 29, 30)], recovery: 11, landingRecovery: 20, totalFrames: 61,
    damage: 1000,
    hits: [
      H("first", 14, 15, 500, { hitLevel: "high", canHitCrouch: true, juggleCost: 4, juggleLimit: 3 }),
      H("second", 29, 30, 500, { hitLevel: "high", canHitCrouch: false, knockdownType: "normal", juggleCost: 4, juggleLimit: 3 }),
    ],
    hit: ADV(null, { state: "knockdown" }), block: ADV(-13), knockdown: KD("normal"), juggle: J([4, 4], [4, 4], [3, 3]),
    tags: ["tatsu", "medium", "multiHit", "firstHitOnlyVsCrouch", "airborne"], animation: "airTatsu",
  }),
  authoredMove({
    id: "tatsuHeavy", name: "Heavy Tatsumaki Senpu-kyaku", category: "special",
    command: CMD("214HK", ["hk"], { motion: "qcb" }),
    startup: 16, activeWindows: [W("first", 16, 17), W("second", 31, 32), W("third", 46, 47)], recovery: 14, landingRecovery: 17, totalFrames: 78,
    damage: 1200,
    hits: [
      H("first", 16, 17, 400, { hitLevel: "high", canHitCrouch: false, juggleCost: 4, juggleLimit: 3 }),
      H("second", 31, 32, 400, { hitLevel: "high", canHitCrouch: false, juggleCost: 4, juggleLimit: 3 }),
      H("third", 46, 47, 400, { hitLevel: "high", canHitCrouch: false, knockdownType: "normal", juggleCost: 4, juggleLimit: 3, limitedJuggle: true }),
    ],
    hit: ADV(null, { state: "knockdown" }), block: ADV(-13), knockdown: KD("normal"), juggle: J([4, 4, 4], [4, 4, 4], [3, 3, 3]),
    tags: ["tatsu", "heavy", "multiHit", "whiffsOnCrouchAfterFirst", "airborne", "lateJuggle"], animation: "airTatsu",
  }),
  authoredMove({
    id: "tatsuOD", name: "Overdrive Tatsumaki Senpu-kyaku", category: "od",
    command: CMD("214KK", ["lk", "mk"], { motion: "qcb", chord: true }), inputAlternatives: ["LK+MK", "LK+HK", "MK+HK"],
    startup: 13,
    activeWindows: [W("first", 13, 14), W("second", 19, 20), W("third", 25, 26), W("fourth", 30, 31), W("fifth", 36, 37)],
    recovery: 10, landingRecovery: 13, totalFrames: 60, damage: 1000,
    hits: [
      H("first", 13, 14, 200, { hitLevel: "high", vacuum: true, juggleCost: 1, juggleLimit: 1 }),
      H("second", 19, 20, 200, { hitLevel: "high", juggleCost: 1, juggleLimit: 3 }),
      H("third", 25, 26, 200, { hitLevel: "high", juggleCost: 1, juggleLimit: 5 }),
      H("fourth", 30, 31, 200, { hitLevel: "high", juggleCost: 1, juggleLimit: 7 }),
      H("fifth", 36, 37, 200, { hitLevel: "high", knockdownType: "normal", juggleCost: 2, juggleLimit: 9 }),
    ],
    hit: ADV(null, { state: "knockdown" }), block: ADV(-14), resource: resource({ drive: 200 }, { label: "2 Drive" }),
    knockdown: KD("normal"), juggle: J("2 ground / 1x5 air", [1, 1, 1, 1, 2], [1, 3, 5, 7, 9]),
    tags: ["tatsu", "od", "multiHit", "vacuum", "airborne", "limitedJuggle"], animation: "airTatsu",
  }),

  // Aerial Tatsumaki and the separate 6HK-cancel branches ----------------
  authoredMove({
    id: "airTatsu", name: "Aerial Tatsumaki Senpu-kyaku", category: "special",
    command: CMD("j.214K", ["mk"], { motion: "qcb", air: true }), inputAlternatives: ["j.214LK", "j.214MK", "j.214HK"],
    startup: 11,
    activeWindows: [W("window1", 11, 12, "spin"), W("window2", 18, 19, "spin"), W("window3", 26, 27, "spin")],
    recovery: 0, landingRecovery: 16, totalFrames: 43, damage: 900,
    hits: [H("spin", 11, 27, 900, { hitLevel: "high", knockdownType: "normal", juggleCost: 1, juggleLimit: 8 })],
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 46, best: 52 }), block: ADV(-6, { bestVsCrouch: 3, crossup: true }),
    knockdown: KD("normal", { advantage: 46 }), juggle: J(5, 1, "8 forward / 3 back"),
    tags: ["air", "tatsu", "singleHitPerTarget", "forwardJumpOnly", "crossUp", "notOverhead", "limitedJuggle"], animation: "airTatsu",
    conditions: ["forwardJump"],
  }),
  authoredMove({
    id: "airTatsuOD", name: "Overdrive Aerial Tatsumaki Senpu-kyaku", category: "od",
    command: CMD("j.214KK", ["lk", "mk"], { motion: "qcb", chord: true, air: true }), inputAlternatives: ["LK+MK", "LK+HK", "MK+HK"],
    startup: 11,
    activeWindows: [W("first", 11, 12), W("second", 14, 16), W("third", 18, 20), W("fourth", 22, 24), W("fifth", 27, 28)],
    recovery: 0, landingRecovery: 16, totalFrames: 44, damage: 1500,
    hits: [
      H("first", 11, 12, 300, { hitLevel: "high", juggleCost: 1, juggleLimit: 10 }),
      H("second", 14, 16, 200, { hitLevel: "high", juggleCost: 1, juggleLimit: 11 }),
      H("third", 18, 20, 200, { hitLevel: "high", juggleCost: 1, juggleLimit: 12 }),
      H("fourth", 22, 24, 200, { hitLevel: "high", juggleCost: 1, juggleLimit: 13 }),
      H("fifth", 27, 28, 600, { hitLevel: "high", knockdownType: "normal", juggleCost: 1, juggleLimit: 14 }),
    ],
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 45, best: 51 }), block: ADV(-29, { worst: -32 }),
    resource: resource({ drive: 200 }, { label: "2 Drive" }), knockdown: KD("normal", { advantage: 45 }),
    juggle: J([1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [10, 11, 12, 13, 14]),
    tags: ["air", "tatsu", "od", "multiHit", "forwardJumpOnly", "notOverhead", "limitedJuggle", "whiffsOnCrouch"], animation: "airTatsu",
    conditions: ["forwardJump"],
  }),
  authoredMove({
    id: "whirlwindAirTatsu", name: "Whirlwind-Cancel Aerial Tatsumaki", category: "special",
    command: CMD("6HK~214K", ["mk"], { motion: "qcb", air: true }), followupFrom: "whirlwindKick",
    startup: 11, activeWindows: [W("spin", 11, 13)], recovery: 13, landingRecovery: 16, totalFrames: 42, damage: 900,
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 38 }), block: ADV(-16),
    knockdown: KD("normal", { advantage: 38 }), juggle: J(4, 4, 3),
    tags: ["air", "tatsu", "branch", "singleHit", "noFollowupJuggle"], animation: "airTatsu",
  }),
  authoredMove({
    id: "whirlwindAirTatsuOD", name: "Whirlwind-Cancel Overdrive Aerial Tatsumaki", category: "od",
    command: CMD("6HK~214KK", ["lk", "mk"], { motion: "qcb", chord: true, air: true }), followupFrom: "whirlwindKick",
    startup: 11,
    activeWindows: [W("first", 11, 12), W("second", 14, 15), W("third", 18, 19), W("fourth", 22, 23), W("fifth", 27, 28)],
    recovery: 12, landingRecovery: 16, totalFrames: 56, damage: 1500,
    hits: [
      H("first", 11, 12, 300, { hitLevel: "high", juggleCost: 1, juggleLimit: 10 }),
      H("second", 14, 15, 200, { hitLevel: "high", juggleCost: 1, juggleLimit: 11 }),
      H("third", 18, 19, 200, { hitLevel: "high", juggleCost: 1, juggleLimit: 12 }),
      H("fourth", 22, 23, 200, { hitLevel: "high", juggleCost: 1, juggleLimit: 13 }),
      H("fifth", 27, 28, 600, { hitLevel: "high", knockdownType: "normal", juggleCost: 1, juggleLimit: 14 }),
    ],
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 47, best: 48 }), block: ADV(-30),
    resource: resource({ drive: 200 }, { label: "2 Drive" }), knockdown: KD("normal", { advantage: 47 }),
    juggle: J([1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [10, 11, 12, 13, 14]),
    tags: ["air", "tatsu", "od", "branch", "multiHit", "hitsCrouch", "cornerFollowup"], animation: "airTatsu",
  }),

  // High Blade Kick --------------------------------------------------------
  authoredMove({
    id: "highBladeLight", name: "Light High Blade Kick", category: "special",
    command: CMD("236LK", ["lk"], { motion: "qcf" }),
    startup: 14, activeWindows: [W("main", 14, 19)], recovery: 22, damage: 1100,
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: [42, 46] }), block: ADV(-11, { bestMeaty: -7 }),
    cancel: cancel("SA3", [cancelWindow(14, 19, SA3_INTO)]),
    knockdown: KD("normal", { advantage: [42, 46] }), juggle: J(1, 1, 10),
    tags: ["donkeyKick", "light", "knockdown", "limitedJuggle", "safeJumpCorner"], animation: "midHeavy",
  }),
  authoredMove({
    id: "highBladeMedium", name: "Medium High Blade Kick", category: "special",
    command: CMD("236MK", ["mk"], { motion: "qcf" }),
    startup: 18, activeWindows: [W("main", 18, 26)], recovery: 19, damage: 1200,
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: [40, 46] }), block: ADV(-8, { bestMeaty: -2 }),
    cancel: cancel("SA3", [cancelWindow(18, 26, SA3_INTO)]),
    knockdown: KD("normal", { advantage: [40, 46] }), juggle: J(1, 1, 10),
    tags: ["donkeyKick", "medium", "knockdown", "limitedJuggle"], animation: "midHeavy",
    whiffRecovery: 22,
  }),
  authoredMove({
    id: "highBladeHeavy", name: "Heavy High Blade Kick", category: "special",
    command: CMD("236HK", ["hk"], { motion: "qcf" }),
    startup: 27, activeWindows: [W("main", 27, 35)], recovery: 15, damage: 1300,
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: [45, 51], punishCounter: "tumbleOTG" }),
    block: ADV(-3, { bestMeaty: 5 }), cancel: cancel("SA3", [cancelWindow(27, 35, SA3_INTO)]),
    knockdown: KD("normal", { advantage: [45, 51], punishCounter: "tumbleOTG" }), juggle: J(1, 1, 10),
    tags: ["donkeyKick", "heavy", "knockdown", "limitedJuggle", "punishTumble", "otg", "cornerFollowup"], animation: "midHeavy",
    cornerFollowups: ["shoryukenMedium", "shoryukenOD", "superArt3", "criticalArt"],
  }),
  authoredMove({
    id: "highBladeOD", name: "Overdrive High Blade Kick", category: "od",
    command: CMD("236KK", ["lk", "mk"], { motion: "qcf", chord: true }), inputAlternatives: ["LK+MK", "LK+HK", "MK+HK"],
    startup: 17, activeWindows: [W("main", 17, 21)], recovery: 33, damage: 800,
    hit: ADV(null, { state: "wallBounce", wallBounceAdvantage: [49, 65] }), block: ADV(-18),
    cancel: cancel("SA2", [cancelWindow(17, 21, SA2_INTO)]), resource: resource({ drive: 200 }, { label: "2 Drive" }),
    knockdown: KD("wallBounce", { advantage: [49, 65] }), juggle: J(1, 2, 10),
    tags: ["donkeyKick", "od", "wallBounce", "limitedJuggle"], animation: "midHeavy",
  }),

  // Hashogeki family -------------------------------------------------------
  authoredMove({
    id: "hashogekiLight", name: "Light Hashogeki", category: "special",
    command: CMD("214LP", ["lp"], { motion: "qcb" }),
    startup: 12, activeWindows: [W("main", 12, 17)], recovery: 18, damage: 700,
    hit: ADV(2, { counter: "spinJuggle", punishCounter: "spinJuggle" }), block: ADV(-3),
    cancel: cancel("SA3", [cancelWindow(12, 17, SA3_INTO)]), juggle: J("1 air", 1, 2),
    tags: ["hashogeki", "light", "projectileClash1", "counterSpin", "strikeHitbox"], animation: "fireballLight",
    projectileClash: { meterlessHits: 1, odHits: 0 }, driveDamageOnBlock: 20,
  }),
  authoredMove({
    id: "hashogekiMedium", name: "Medium Hashogeki", category: "special",
    command: CMD("214MP", ["mp"], { motion: "qcb" }),
    startup: 19, activeWindows: [W("main", 19, 24)], recovery: 17, damage: 800,
    hit: ADV(2, { counter: "spinJuggle", punishCounter: "spinJuggle" }), block: ADV(-6),
    cancel: cancel("SA3", [cancelWindow(19, 24, SA3_INTO)]), juggle: J("1 air", 1, 2),
    tags: ["hashogeki", "medium", "projectileClash1", "counterSpin", "strikeHitbox"], animation: "fireballHeavy",
    projectileClash: { meterlessHits: 1, odHits: 0 },
  }),
  authoredMove({
    id: "hashogekiHeavy", name: "Heavy Hashogeki", category: "special",
    command: CMD("214HP", ["hp"], { motion: "qcb" }),
    startup: 30, activeWindows: [W("first", 30, 35), W("second", 30, 35)], recovery: 19, damage: 800,
    hits: [
      H("first", 30, 35, 400, { hitLevel: "high", juggleCost: 1, juggleLimit: 0 }),
      H("second", 30, 35, 400, { hitLevel: "high", knockdownType: "spin", juggleCost: 1, juggleLimit: 1 }),
    ],
    hit: ADV(null, { state: "spin", knockdownAdvantage: 61 }), block: ADV(2),
    cancel: cancel("SA3", [cancelWindow(30, 35, SA3_INTO)]), knockdown: KD("spin", { advantage: 61 }),
    juggle: J([1, 1], [1, 1], [0, 1]), tags: ["hashogeki", "heavy", "multiHit", "spin", "projectileClash1", "strikeHitbox"], animation: "fireballHeavy",
    projectileClash: { meterlessHits: 1, odHits: 0 }, simultaneousHitWindows: true,
  }),
  authoredMove({
    id: "hashogekiDenjin", name: "Denjin Hashogeki", category: "special",
    command: CMD("214HP (Denjin)", ["hp"], { motion: "qcb" }),
    startup: 20, activeWindows: [W("first", 20, 25), W("second", 20, 25)], recovery: 19, damage: 800,
    hits: [
      H("first", 20, 25, 400, { hitLevel: "high", juggleCost: 1, juggleLimit: 3 }),
      H("second", 20, 25, 400, { hitLevel: "high", knockdownType: "spin", juggleCost: 1, juggleLimit: 4 }),
    ],
    hit: ADV(null, { state: "spin", knockdownAdvantage: 62 }), block: ADV(3),
    cancel: cancel("SA3", [cancelWindow(20, 25, SA3_INTO)]),
    resource: resource({}, { consumes: { denjin: 1 }, conditions: ["denjinStock>=1", "heavyPunchStrength"], label: "Denjin ×1" }),
    knockdown: KD("spin", { advantage: 62 }), juggle: J([1, 1], [1, 1], [3, 4]),
    tags: ["hashogeki", "heavy", "denjin", "multiHit", "spin", "projectileClash2", "strikeHitbox"], animation: "fireballHeavy",
    projectileClash: { meterlessHits: 2, odHits: 0 }, simultaneousHitWindows: true,
  }),
  authoredMove({
    id: "hashogekiOD", name: "Overdrive Hashogeki", category: "od",
    command: CMD("214PP", ["lp", "mp"], { motion: "qcb", chord: true }), inputAlternatives: ["LP+MP", "LP+HP", "MP+HP"],
    startup: 18, activeWindows: [W("main", 18, 22)], recovery: 20, totalFrames: 42, damage: 1100,
    hit: ADV(3), block: ADV(3), cancel: cancel("SA2", [cancelWindow(18, 22, SA2_INTO)]),
    resource: resource({ drive: 200 }, { label: "2 Drive" }), juggle: J("1 air", 1, 1),
    tags: ["hashogeki", "od", "plusOnBlock", "projectileClashOD1", "strikeHitbox"], animation: "fireballHeavy",
    projectileClash: { meterlessHits: "any", odHits: 1 },
  }),
  authoredMove({
    id: "hashogekiODDenjin", name: "Denjin Overdrive Hashogeki", category: "od",
    command: CMD("214PP (Denjin)", ["lp", "mp"], { motion: "qcb", chord: true }), inputAlternatives: ["LP+MP", "LP+HP", "MP+HP"],
    startup: 18, activeWindows: [W("main", 18, 23)], recovery: 19, damage: 800,
    hit: ADV(null, { state: "crumple", knockdownAdvantage: 87, airborneAfter: 14 }), block: ADV(4),
    cancel: cancel("SA2", [cancelWindow(18, 23, SA2_INTO)]),
    resource: resource({ drive: 200 }, { consumes: { denjin: 1 }, conditions: ["denjinStock>=1"], label: "2 Drive + Denjin ×1" }),
    knockdown: KD("crumple", { advantage: 87, airborneAfter: 14 }), juggle: J("-1 ground / 1 air", 1, 2),
    tags: ["hashogeki", "od", "denjin", "crumple", "plusOnBlock", "projectileClashOD1", "strikeHitbox"], animation: "fireballHeavy",
    projectileClash: { meterlessHits: "any", odHits: 1 },
  }),
  authoredMove({
    id: "denjinCharge", name: "Denjin Charge", category: "special",
    command: CMD("22P", ["hp"], { motion: "downDown" }), inputAlternatives: ["22LP", "22MP", "22HP"],
    startup: 50, activeWindows: [W("stockGain", 50)], recovery: 2, totalFrames: 52, damage: 0, hitLevel: "none",
    hit: ADV(null, { state: "resourceGain" }), block: ADV(null),
    resource: resource({}, { gains: { denjin: 1, frame: 51 }, conditions: ["denjinStock<1"], label: "Gain Denjin ×1" }),
    juggle: J(), tags: ["charge", "resourceGain", "counterStateAllFrames", "maxOneStock"], animation: "fireballHeavy",
    maxStock: 1, persistsBetweenRounds: false,
  }),

  // Super Arts -------------------------------------------------------------
  authoredMove({
    id: "superArt1", name: "Shinku Hadoken", category: "super",
    command: CMD("236236P", ["hp"], { motion: "qcfQcf" }), inputAlternatives: ["236236LP", "236236MP", "236236HP"],
    startup: 7,
    activeWindows: [W("hit1", 7), W("hit2", 7), W("hit3", 7), W("hit4", 7), W("hit5", 7)],
    recovery: 79, totalFrames: 86, damage: 2000,
    hits: [1, 2, 3, 4, 5].map((index) => H(`hit${index}`, 7, 7, 400, {
      hitLevel: "high", knockdownType: index === 5 ? "normal" : undefined,
      juggleCost: index === 5 ? 100 : 1, juggleLimit: 99,
    })),
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 26 }), block: ADV(-24),
    resource: resource({ super: 100 }, { label: "1 Super" }), knockdown: KD("normal", { advantage: 26 }),
    juggle: J([1, 1, 1, 1, 100], [1, 1, 1, 1, 100], [99, 99, 99, 99, 99]),
    tags: ["sa1", "projectile", "multiHit", "knockdown", "minimumScale30"], animation: "fireballHeavy",
    invulnerability: [{ start: 1, end: 8, type: "strikeThrow" }], minimumScaling: 0.3,
    projectile: { hits: 5, localActive: false, canCoexistWithODHadoken: true },
  }),
  authoredMove({
    id: "superArt1Denjin", name: "Denjin Hadoken", category: "super",
    command: CMD("236236P (Denjin)", ["hp"], { motion: "qcfQcf" }), inputAlternatives: ["236236LP", "236236MP", "236236HP"],
    startup: 7,
    activeWindows: [W("hit1", 7), W("hit2", 7), W("hit3", 7), W("hit4", 7), W("hit5", 7), W("hit6", 7), W("hit7", 7), W("hit8", 7)],
    recovery: 82, totalFrames: 89, damage: 2400,
    hits: [1, 2, 3, 4, 5, 6, 7, 8].map((index) => H(`hit${index}`, 7, 7, index === 8 ? 1000 : 200, {
      hitLevel: "high", knockdownType: index === 8 ? "normal" : undefined,
      juggleCost: index === 8 ? 100 : 1, juggleLimit: 99,
    })),
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 27 }), block: ADV(-24),
    resource: resource({ super: 100 }, { consumes: { denjin: 1 }, conditions: ["denjinStock>=1"], label: "1 Super + Denjin ×1" }),
    knockdown: KD("normal", { advantage: 27 }),
    juggle: J([1, 1, 1, 1, 1, 1, 1, 100], [1, 1, 1, 1, 1, 1, 1, 100], Array(8).fill(99)),
    tags: ["sa1", "projectile", "denjin", "multiHit", "knockdown", "minimumScale30"], animation: "fireballHeavy",
    invulnerability: [{ start: 1, end: 8, type: "strikeThrow" }], minimumScaling: 0.3,
    projectile: { hits: 8, localActive: false, canCoexistWithODHadoken: true },
  }),
  authoredMove({
    id: "superArt2Level1", name: "Shin Hashogeki Level 1", category: "super",
    command: CMD("214214P", ["hp"], { motion: "qcbQcb" }),
    inputAlternatives: ["214214LP", "214214MP", "214214HP"],
    startup: 12, activeWindows: [W("burst", 12, 17)], recovery: 39, totalFrames: 56, damage: 2800,
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 20 }), block: ADV(-20),
    resource: resource({ super: 200 }, { label: "2 Super" }), knockdown: KD("normal", { advantage: 20 }), juggle: J(1, 1, 99),
    tags: ["sa2", "level1", "chargeable", "strikeHitbox", "minimumScale40"], animation: "fireballHeavy",
    invulnerability: [{ start: 1, end: 13, type: "full" }], minimumScaling: 0.4, chargeFrames: { level2After: 7, level3After: 39 },
  }),
  authoredMove({
    id: "superArt2Level1Denjin", name: "Denjin Hashogeki Level 1", category: "super",
    command: CMD("214214P (Denjin)", ["hp"], { motion: "qcbQcb" }),
    inputAlternatives: ["214214LP", "214214MP", "214214HP"],
    startup: 12, activeWindows: [W("burst", 12, 17)], recovery: 39, totalFrames: 56, damage: 3200,
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 20 }), block: ADV(-20),
    resource: resource({ super: 200 }, { consumes: { denjin: 1 }, conditions: ["denjinStock>=1"], label: "2 Super + Denjin ×1" }),
    knockdown: KD("normal", { advantage: 20 }), juggle: J(1, 1, 99),
    tags: ["sa2", "level1", "denjin", "chargeable", "strikeHitbox", "minimumScale40"], animation: "fireballHeavy",
    invulnerability: [{ start: 1, end: 13, type: "full" }], minimumScaling: 0.4, chargeFrames: { level2After: 7, level3After: 39 },
  }),
  authoredMove({
    id: "superArt2Level2", name: "Shin Hashogeki Level 2", category: "super",
    command: CMD("214214P (hold >7F)", ["hp"], { motion: "qcbQcb", hold: true }),
    inputAlternatives: ["214214LP", "214214MP", "214214HP"],
    startup: 20, activeWindows: [W("burst", 20, 25)], recovery: 39, totalFrames: 64, damage: 2900,
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 20 }), block: ADV(-20),
    resource: resource({ super: 200 }, { conditions: ["holdFrames>7", "holdFrames<=39"], label: "2 Super" }),
    knockdown: KD("normal", { advantage: 20 }), juggle: J(1, 1, 99),
    tags: ["sa2", "level2", "charged", "strikeHitbox", "minimumScale40"], animation: "fireballHeavy",
    invulnerability: [{ start: 1, end: 9, type: "full" }], minimumScaling: 0.4, holdThreshold: 7,
  }),
  authoredMove({
    id: "superArt2Level2Denjin", name: "Denjin Hashogeki Level 2", category: "super",
    command: CMD("214214P (Denjin, hold >7F)", ["hp"], { motion: "qcbQcb", hold: true }),
    inputAlternatives: ["214214LP", "214214MP", "214214HP"],
    startup: 20, activeWindows: [W("burst", 20, 25)], recovery: 39, totalFrames: 64, damage: 3300,
    hit: ADV(null, { state: "tumbleOTG", knockdownAdvantage: 78 }), block: ADV(-20),
    resource: resource({ super: 200 }, {
      consumes: { denjin: 1 }, conditions: ["denjinStock>=1", "holdFrames>7", "holdFrames<=39"], label: "2 Super + Denjin ×1",
    }),
    knockdown: KD("tumbleOTG", { advantage: 78 }), juggle: J(1, 1, 99),
    tags: ["sa2", "level2", "denjin", "charged", "tumble", "otg", "minimumScale40", "comboScale20"], animation: "fireballHeavy",
    invulnerability: [{ start: 1, end: 9, type: "full" }], minimumScaling: 0.4, comboScaling: 0.2, holdThreshold: 7,
  }),
  authoredMove({
    id: "superArt2Level3", name: "Shin Hashogeki Level 3", category: "super",
    command: CMD("214214P (hold >39F)", ["hp"], { motion: "qcbQcb", hold: true }),
    inputAlternatives: ["214214LP", "214214MP", "214214HP"],
    startup: 70, activeWindows: [W("burst", 70, 75)], recovery: 39, totalFrames: 114, damage: 3000,
    hit: ADV(null, { state: "tumbleOTG", knockdownAdvantage: 78 }), block: ADV(-20),
    resource: resource({ super: 200 }, { conditions: ["holdFrames>39"], label: "2 Super" }),
    knockdown: KD("tumbleOTG", { advantage: 78 }), juggle: J(1, 1, 99),
    tags: ["sa2", "level3", "fullyCharged", "tumble", "otg", "strikeHitbox", "minimumScale40"], animation: "fireballHeavy",
    invulnerability: [{ start: 1, end: 9, type: "full" }], minimumScaling: 0.4, holdThreshold: 39,
  }),
  authoredMove({
    id: "superArt2Level3Denjin", name: "Denjin Hashogeki Level 3", category: "super",
    command: CMD("214214P (Denjin, hold >39F)", ["hp"], { motion: "qcbQcb", hold: true }),
    inputAlternatives: ["214214LP", "214214MP", "214214HP"],
    startup: 70, activeWindows: [W("burst", 70, 75)], recovery: 39, totalFrames: 114, damage: 3400,
    hit: ADV(null, { state: "tumbleOTG", knockdownAdvantage: 78 }), block: ADV(-20),
    resource: resource({ super: 200 }, { consumes: { denjin: 1 }, conditions: ["denjinStock>=1", "holdFrames>39"], label: "2 Super + Denjin ×1" }),
    knockdown: KD("tumbleOTG", { advantage: 78 }), juggle: J(1, 1, 99),
    tags: ["sa2", "level3", "denjin", "fullyCharged", "tumble", "otg", "strikeHitbox", "minimumScale40"], animation: "fireballHeavy",
    invulnerability: [{ start: 1, end: 9, type: "full" }], minimumScaling: 0.4, holdThreshold: 39,
  }),
  authoredMove({
    id: "superArt3", name: "Shin Shoryuken", category: "super",
    command: CMD("236236K", ["hk"], { motion: "qcfQcf" }), inputAlternatives: ["236236LK", "236236MK", "236236HK"],
    startup: 5, activeWindows: [W("cinematic", 5, 16)], recovery: 71, totalFrames: 87, damage: 4000,
    hits: [H("cinematic", 5, 16, 4000, { hitLevel: "high", knockdownType: "hard", juggleCost: 1, juggleLimit: 99, nonCinematicLateDamage: 3600 })],
    hit: ADV(null, { state: "hardKnockdown", knockdownAdvantage: 14 }), block: ADV(-52),
    resource: resource({ super: 300 }, { label: "3 Super" }), knockdown: KD("hard", { advantage: 14 }), juggle: J(1, 1, 99),
    tags: ["sa3", "cinematic", "hardKnockdown", "minimumScale50", "specialCancelOnly"], animation: "dragonPunch",
    invulnerability: [{ start: 1, end: 16, type: "full" }], minimumScaling: 0.5,
    cancelStartupOverride: { from: "shoryukenHeavy", startup: 2 },
  }),
  authoredMove({
    id: "criticalArt", name: "Shin Shoryuken (Critical Art)", category: "climax",
    command: CMD("236236K (HP≤25%)", ["hk"], { motion: "qcfQcf" }), inputAlternatives: ["236236LK", "236236MK", "236236HK"],
    startup: 5, activeWindows: [W("cinematic", 5, 16)], recovery: 71, totalFrames: 87, damage: 4500,
    hits: [H("cinematic", 5, 16, 4500, { hitLevel: "high", knockdownType: "hard", juggleCost: 1, juggleLimit: 99, nonCinematicLateDamage: 4400 })],
    hit: ADV(null, { state: "hardKnockdown", knockdownAdvantage: 14 }), block: ADV(-52),
    resource: resource({ super: 300 }, { conditions: ["healthRatio<=0.25"], label: "3 Super · HP≤25%" }),
    knockdown: KD("hard", { advantage: 14 }), juggle: J(1, 1, 99),
    tags: ["ca", "cinematic", "hardKnockdown", "minimumScale50", "lowHealthOnly", "specialCancelOnly"], animation: "dragonPunch",
    invulnerability: [{ start: 1, end: 16, type: "full" }], minimumScaling: 0.5,
    cancelStartupOverride: { from: "shoryukenHeavy", startup: 2 },
  }),

  // Universal Drive / movement rows ---------------------------------------
  authoredMove({
    id: "forwardDash", name: "Forward Dash", category: "system",
    command: CMD("66", [], { motion: "forwardForward" }),
    startup: 1, activeWindows: [W("movement", 1, 19)], recovery: 0, totalFrames: 19, damage: 0, hitLevel: "none",
    hit: ADV(null, { state: "movement" }), block: ADV(null), juggle: J(),
    tags: ["movement", "dash", "forward", "nonAttack"], animation: "dash",
  }),
  authoredMove({
    id: "backDash", name: "Back Dash", category: "system",
    command: CMD("44", [], { motion: "backBack" }),
    startup: 1, activeWindows: [W("movement", 1, 23)], recovery: 0, totalFrames: 23, damage: 0, hitLevel: "none",
    hit: ADV(null, { state: "movement" }), block: ADV(null), juggle: J(),
    tags: ["movement", "dash", "back", "throwInvulnerableF1to15", "nonAttack"], animation: "dash",
    invulnerability: [{ start: 1, end: 15, type: "throw" }],
  }),
  authoredMove({
    id: "driveImpact", name: "Shingeki (Drive Impact)", category: "system",
    command: CMD("HP+HK", ["hp", "hk"], { chord: true }),
    startup: 26, activeWindows: [W("impact", 26, 27)], recovery: 35, damage: 800,
    hit: ADV(null, {
      state: "knockdown", knockdownAdvantage: 35, wallSplatAdvantage: 65,
      punishCounter: "crumple", armorAbsorbHit: "crumple", airbornePunish: "spin",
    }),
    block: ADV(-3, { corner: "wallSplatHardKnockdown", cornerAdvantage: 72 }),
    resource: resource({ drive: 100 }, { label: "1 Drive" }), knockdown: KD("conditional", {
      normal: "knockdown", punishCounter: "crumple", corner: "wallSplat", airborne: "spin",
    }),
    juggle: J(0, 1, 0), tags: ["driveImpact", "armor", "wallSplat", "crumple", "systemAttack"], animation: "midHeavy",
    armor: { start: 1, end: 27, hits: 2 },
  }),
  authoredMove({
    id: "driveReversalBlock", name: "Chest Strike (Drive Reversal: Block)", category: "system",
    command: CMD("blockstun 6+HP+HK", ["hp", "hk"], { chord: true, direction: "forward" }),
    startup: 20, activeWindows: [W("reversal", 20, 22)], recovery: 26, totalFrames: 48, damage: 500,
    hits: [H("reversal", 20, 22, 500, { hitLevel: "high", knockdownType: "normal", juggleCost: 100, juggleLimit: 1, recoverableDamage: true })],
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 23, extraRecovery: 5, recoverableDamage: true }), block: ADV(-6),
    resource: resource({ drive: 200 }, { conditions: ["inBlockstun"], label: "2 Drive" }),
    knockdown: KD("normal", { advantage: 23 }), juggle: J(200, 100, 1),
    tags: ["driveReversal", "blockstunOnly", "reversal", "recoverableDamage", "systemAttack"], animation: "midHeavy",
    invulnerability: [{ start: 1, end: 22, type: "full" }], hitRecovery: 31,
  }),
  authoredMove({
    id: "driveReversalWakeup", name: "Chest Strike (Drive Reversal: Recovery)", category: "system",
    command: CMD("wakeup hold 6+HP+HK", ["hp", "hk"], { chord: true, direction: "forward", hold: true }),
    startup: 18, activeWindows: [W("reversal", 18, 20)], recovery: 26, totalFrames: 46, damage: 500,
    hits: [H("reversal", 18, 20, 500, { hitLevel: "high", knockdownType: "normal", juggleCost: 100, juggleLimit: 1, recoverableDamage: true })],
    hit: ADV(null, { state: "knockdown", knockdownAdvantage: 23, extraRecovery: 5, recoverableDamage: true }), block: ADV(-6),
    resource: resource({ drive: 200 }, { conditions: ["wakeupRecovery"], label: "2 Drive" }),
    knockdown: KD("normal", { advantage: 23 }), juggle: J(200, 100, 1),
    tags: ["driveReversal", "wakeupOnly", "reversal", "recoverableDamage", "systemAttack"], animation: "midHeavy",
    invulnerability: [{ start: 1, end: 20, type: "full" }], hitRecovery: 31,
  }),
  authoredMove({
    id: "driveParry", name: "Drive Parry", category: "system",
    command: CMD("MP+MK", ["mp", "mk"], { chord: true, hold: true }),
    startup: 1, activeWindows: [W("parry", 1, 12)], recovery: 33, totalFrames: 45, damage: 0, hitLevel: "none",
    hit: ADV(null, { state: "parry" }), block: ADV(null),
    cancel: cancel("parry-drive-rush", [cancelWindow(4, 12, ["system"], {
      on: ["always"], moves: ["parryDriveRush"], requiresContact: false,
    })]),
    resource: resource({}, { continuousCost: "driveParry", label: "Continuous Drive" }), juggle: J(),
    tags: ["parry", "holdable", "counterVulnerable", "nonAttack"], animation: "guard",
    holdExtension: true,
  }),
  authoredMove({
    id: "perfectParryStrike", name: "Perfect Parry (Strike)", category: "system",
    command: CMD("timed MP+MK", ["mp", "mk"], { chord: true }),
    startup: 1, activeWindows: [W("perfectWindow", 1, 2)], recovery: 1, totalFrames: 3, damage: 0, hitLevel: "none",
    hit: ADV(null, { state: "perfectParry", postFreezeInvulnerability: 5 }), block: ADV(null),
    resource: resource({}, { conditions: ["parryWithinPerfectWindow", "directionMatchesAttackLevel"], label: "Parry timing" }),
    juggle: J(), tags: ["perfectParry", "strike", "starterScale50", "nonAttack"], animation: "guard",
    initialProration: 0.5, postRecoveryInvulnerability: 5,
  }),
  authoredMove({
    id: "perfectParryProjectile", name: "Perfect Parry (Projectile)", category: "system",
    command: CMD("timed MP+MK vs projectile", ["mp", "mk"], { chord: true }),
    startup: 1, activeWindows: [W("perfectWindow", 1, 2)], recovery: 10, totalFrames: 12, damage: 0, hitLevel: "none",
    hit: ADV(null, { state: "perfectParryProjectile", screenFreeze: false }), block: ADV(null),
    resource: resource({}, { conditions: ["parryWithinPerfectWindow", "incomingProjectile"], label: "Parry timing" }),
    juggle: J(), tags: ["perfectParry", "projectile", "starterScale50", "noScreenFreeze", "nonAttack"], animation: "guard",
    initialProration: 0.5,
  }),
  authoredMove({
    id: "parryDriveRush", name: "Parry Drive Rush", category: "system",
    command: CMD("MP+MK~66", ["mp", "mk"], { motion: "forwardForward", chord: true }),
    startup: 4, activeWindows: [W("rush", 4, 23)], recovery: 22, totalFrames: 45, damage: 0, hitLevel: "none",
    hit: ADV(null, { state: "driveRush" }), block: ADV(null),
    cancel: cancel("action", [cancelWindow(9, 23, ["normal", "commandNormal", "targetCombo", "throw", "special", "od", "system"], {
      on: ["always"], requiresContact: false,
    })]),
    resource: resource({ drive: 100 }, { label: "1 Drive" }), juggle: J(),
    tags: ["driveRush", "parryRoute", "attackEarliestF9", "otherActionF24", "nonAttack"], animation: "dash",
    earliestAttackFrame: 9, earliestOtherActionFrame: 24,
  }),
  authoredMove({
    id: "cancelDriveRush", name: "Drive Rush Cancel", category: "system",
    command: CMD("cancelable normal~66 / 5/6+MP+MK", ["mp", "mk"], { motion: "forwardForward", chord: true }),
    startup: 1, activeWindows: [W("rush", 1, 24)], recovery: 22, totalFrames: 46, damage: 0, hitLevel: "none",
    hit: ADV(null, { state: "driveRushCancel" }), block: ADV(null),
    cancel: cancel("action", [cancelWindow(10, 24, ["normal", "commandNormal", "targetCombo", "throw", "special", "od", "system"], {
      on: ["always"], requiresContact: false,
    })]),
    resource: resource({ drive: 300 }, { conditions: ["sourceMoveHasDriveRushCancel"], label: "3 Drive" }), juggle: J(),
    tags: ["driveRush", "normalCancelRoute", "attackEarliestF10", "otherActionF25", "nonAttack"], animation: "dash",
    earliestAttackFrame: 10, earliestOtherActionFrame: 25,
  }),
  authoredMove({
    id: "throwEscape", name: "Throw Escape", category: "system",
    command: CMD("LP+LK during throw-tech window", ["lp", "lk"], { chord: true }),
    startup: 1, activeWindows: [W("tech", 1)], recovery: 0, totalFrames: 1, damage: 0, hitLevel: "none",
    hit: ADV(null, { state: "throwEscape" }), block: ADV(null),
    resource: resource({}, { gains: { drive: 50 }, conditions: ["insideThrowTechWindow"], label: "Gain 0.5 Drive" }),
    juggle: J(), tags: ["throwTech", "universal", "nonAttack"], animation: "guard",
  }),

  // Operable but non-combat taunts (community-measured total durations). ---
  authoredMove({
    id: "neutralTaunt", name: "Neutral Taunt", category: "system",
    command: CMD("5+PPP+KKK", ["lp", "mp", "hp", "lk", "mk", "hk"], { chord: true, direction: "neutral" }),
    startup: 210, activeWindows: [W("complete", 210)], recovery: 0, totalFrames: 210, damage: 0, hitLevel: "none",
    hit: ADV(null), block: ADV(null), juggle: J(), tags: ["taunt", "nonCombat", "nonAttack"], animation: "idle",
  }),
  authoredMove({
    id: "forwardTaunt", name: "Forward Taunt", category: "system",
    command: CMD("6+PPP+KKK", ["lp", "mp", "hp", "lk", "mk", "hk"], { chord: true, direction: "forward" }),
    startup: 124, activeWindows: [W("complete", 124)], recovery: 0, totalFrames: 124, damage: 0, hitLevel: "none",
    hit: ADV(null), block: ADV(null), juggle: J(), tags: ["taunt", "nonCombat", "nonAttack"], animation: "idle",
  }),
  authoredMove({
    id: "backTaunt", name: "Back Taunt", category: "system",
    command: CMD("4+PPP+KKK", ["lp", "mp", "hp", "lk", "mk", "hk"], { chord: true, direction: "back" }),
    startup: 209, activeWindows: [W("complete", 209)], recovery: 0, totalFrames: 209, damage: 0, hitLevel: "none",
    hit: ADV(null), block: ADV(null), juggle: J(), tags: ["taunt", "nonCombat", "nonAttack"], animation: "idle",
  }),
  authoredMove({
    id: "downTaunt", name: "Down Taunt", category: "system",
    command: CMD("2+PPP+KKK", ["lp", "mp", "hp", "lk", "mk", "hk"], { chord: true, direction: "down" }),
    startup: 154, activeWindows: [W("complete", 154)], recovery: 0, totalFrames: 154, damage: 0, hitLevel: "none",
    hit: ADV(null), block: ADV(null), juggle: J(), tags: ["taunt", "nonCombat", "nonAttack"], animation: "idle",
  }),
];

export const VANGUARD_MOVESET = defineMoveset({
  id: "vanguard",
  name: "Vanguard",
  archetype: "fundamentals / shoto",
  controlLayout: "sixButton",
  resourceModel: "vanguard",
  aliases: {
    highLight: "standLightPunch",
    highHeavy: "standHeavyPunch",
    midLight: "collarboneBreaker",
    midHeavy: "solarPlexusStrike",
    lowLight: "crouchLightKick",
    lowHeavy: "crouchHeavyKick",
    fireballLight: "hadokenLight",
    fireballHeavy: "hadokenHeavy",
    dragonPunch: "shoryukenLight",
    airLight: "jumpLightPunch",
    airHeavy: "jumpHeavyKick",
    airTatsu: "airTatsu",
    throw: "shoulderThrow",
  },
  moves: MOVES,
});

export default VANGUARD_MOVESET;
